### ISSUE TITLE
希望能够自定义邮箱来发送邮件，同时邮箱的账号密码使用secret来填充

### ISSUE THREAD

**Issue by davidelectricfree** [srcrs/UnicomTask#10]
这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。

**Comment by srcrs** [comment]
> 这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
> 看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。

server酱在4月底就只能企业微信才能用了，以后可以考虑通过钉钉机器人等类似产品，所以暂时先用邮箱来代替。若使用使用自定义邮箱，配置较麻烦，要开通smtp功能。先观察一段时间吧。

**Comment by davidelectricfree** [comment]
> 
> 
> > 这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
> > 看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。
> 
> server酱在4月底就只能企业微信才能用了，以后可以考虑通过钉钉机器人等类似产品，所以暂时先用邮箱来代替。若使用使用自定义邮箱，配置较麻烦，要开通smtp功能。先观察一段时间吧。

感谢回复，关于邮箱这一块https://github.com/dawidd6/action-send-mail，另外，看到最新的使用了流量云的api来发邮件，看可不可以把代码里面的`  logger.info('【登录】: ' + result['default'][-4:])` 改成`  logger.info('【登录】: ' + 登陆状态)` ，这样手机后四位不会出现在邮件中，谢谢。

**Comment by davidelectricfree** [comment]
> 
> 
> > 这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
> > 看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。
> 
> server酱在4月底就只能企业微信才能用了，以后可以考虑通过钉钉机器人等类似产品，所以暂时先用邮箱来代替。若使用使用自定义邮箱，配置较麻烦，要开通smtp功能。先观察一段时间吧。

我这边可以写一个

> 
> 
> > 这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
> > 看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。
> 
> server酱在4月底就只能企业微信才能用了，以后可以考虑通过钉钉机器人等类似产品，所以暂时先用邮箱来代替。若使用使用自定义邮箱，配置较麻烦，要开通smtp功能。先观察一段时间吧。

我这边可以写一个server酱的推送函数放到你的notify里面吗？然后给你推送过来

**Comment by srcrs** [comment]
> > 
> > 
> > > 这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
> > > 看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。
> > 
> > server酱在4月底就只能企业微信才能用了，以后可以考虑通过钉钉机器人等类似产品，所以暂时先用邮箱来代替。若使用使用自定义邮箱，配置较麻烦，要开通smtp功能。先观察一段时间吧。
> 
> 
> 另外，我这边可以写一个server酱的推送函数放到你的notify里面吗？然后给你推送过来

可以的，欢迎😄

**Comment by davidelectricfree** [comment]
> > > 
> > > 
> > > > 这个工具非常好用，这个提一个小小的建议，看当前是使用一个公共邮箱来发送邮件的。
> > > > 看是否能够自定义邮箱来发送邮件，邮箱的账号密码使用secret来填充。或者使用server酱[http://sc.ftqq.com/3.versionServer](url)的接口来进行推送。万分感谢。
> > > 
> > > server酱在4月底就只能企业微信才能用了，以后可以考虑通过钉钉机器人等类似产品，所以暂时先用邮箱来代替。若使用使用自定义邮箱，配置较麻烦，要开通smtp功能。先观察一段时间吧。
> > 
> > 
> > 另外，我这边可以写一个server酱的推送函数放到你的notify里面吗？然后给你推送过来
> 
> 可以的，欢迎😄

试了，企业微信数据有截断，超过240字节就自动截断了，无法全部显示，要动从主程序那边来的消息，算了，还是就这样吧，用邮箱算了。
