### ISSUE TITLE
领取的流量怎么用

### ISSUE THREAD

**Issue by wwd66565** [srcrs/UnicomTask#100]
【登录】: 1310 【每日签到】: 打卡成功,翻倍成功 【1G流量日包】: 领取成功 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 【积分抽奖】: 谢谢参与~ x1 【积分抽奖】: 谢谢参与~ x2 【积分抽奖】: 谢谢参与~ x3 【100定向积分】: 领取成功 【东奥积分活动】: 领取成功，300积分 【沃之树-领流量】: 4M流量 x1 【沃之树-领流量】: 4M流量 x2 【沃之树-领流量】: 4M流量 x3 【沃之树-浇水】: 获得3培养值 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过 【100M寻宝箱】: 任务失败 【4G流量包-看视频】: 获得30M流量 x1 【4G流量包-下软件】: 获得50M流量 x1 【4G流量包-看视频】: 获得30M流量 x2 【4G流量包-下软件】: 获得50M流量 x2 【4G流量包-看视频】: 获得30M流量 x3 【4G流量包-下软件】: 获得50M流量 x3

**Comment by srcrs** [comment]
在 “我的” --》 我的礼包，就能看到了

**Comment by wwd66565** [comment]
感谢，原来是20元卡不能兑换那些2MB，怪不得没有

**Comment by srcrs** [comment]
> 感谢，原来是20元卡不能兑换那些2MB，怪不得没有

2M等到累计成100M就可以兑了的
