### ISSUE TITLE
多账户格式问题

### ISSUE THREAD

**Issue by 1027557839** [srcrs/UnicomTask#101]
[
    {
        "username": "xxxxxxxxxxx",
        "password": "xxxxxx",
        "appId": "06eccb0b7c2fd02bc1bb5e8a9ca2874175912935739f04e10c99e01105203a8893b8a784484c85ae5b97db8c75cda67fea99cd83b52982a0bcbed0e51408fad1c1bacf87c64f581bffb3db8ea2cf0f81"
    }，
    {
        "username": "xxxxxxccxx",
        "password": "xxxxxxx",
        "appId": "06eccb0b7c2fd02bc1bb5e8a9ca2874175912935739f04e10c99e01105203a8893b8a784484c85ae5b97db8c75cda67fea99cd83b52982a0bcbed0e51408fad1c1bacf87c64f581bffb3db8ea2cf0f81"
    }，
    {
        "username": "1xxxxxxxxx",
        "password": "xxxxxx",
        "appId": "06eccb0b7c2fd02bc1bb5e8a9ca2874175912935739f04e10c99e01105203a8893b8a784484c85ae5b97db8c75cda67fea99cd83b52982a0bcbed0e51408fad1c1bacf87c64f581bffb3db8ea2cf0f81"
    }，
    {
        "username": "xxxxxxxxx",
        "password": "xxxxxx",
        "appId": "06eccb0b7c2fd02bc1bb5e8a9ca2874175912935739f04e10c99e01105203a8893b8a784484c85ae5b97db8c75cda67fea99cd83b52982a0bcbed0e51408fad1c1bacf87c64f581bffb3db8ea2cf0f81"
    }
]

**Comment by 1027557839** [comment]
这格式有问题吗 怎么改都是提示格式错误

**Comment by srcrs** [comment]
@1027557839 有的逗号是中文的

**Comment by 1027557839** [comment]
解决了 谢谢大佬 还有一个问题 为啥手动运行只做几个任务就完了

**Comment by srcrs** [comment]
> 解决了 谢谢大佬 还有一个问题 为啥手动运行只做几个任务就完了

本项目能做的任务不太多
