### ISSUE TITLE
可以增加iOS的Bark推送信息吗

### ISSUE THREAD

**Issue by Zoenzao** [srcrs/UnicomTask#102]
Bark挺好的

**Comment by srcrs** [comment]
> Bark挺好的

你那边有方法可以提pr哦，我对这个推送不是很熟悉

**Comment by Kelvinhou327** [comment]
> > Bark挺好的
> 
> 你那边有方法可以提pr哦，我对这个推送不是很熟悉


https://api.day.app/XXXXX/推送标题/推送内容

完整的get请求 ，XXXXX即是自己Bark的Key，请求成功就会借助Apple推送服务器推送到手机。

**Comment by Kelvinhou327** [comment]
> > > Bark挺好的
> > 
> > 
> > 你那边有方法可以提pr哦，我对这个推送不是很熟悉
> 
> [https://api.day.app/XXXXX/推送标题/推送内容](https://api.day.app/XXXXX/%E6%8E%A8%E9%80%81%E6%A0%87%E9%A2%98/%E6%8E%A8%E9%80%81%E5%86%85%E5%AE%B9)
> 
> 完整的get请求 ，XXXXX即是自己Bark的Key，请求成功就会借助Apple推送服务器推送到手机。
#发送Bark通知
def sendBark(key):
    try:
        key = Brak_Key
        #发送内容
        content = readFile_text('./log.txt')
        data = {
            'UnicomTask每日报表':content
        }
        content = urllib.parse.urlencode(data)
        requests.get('https://api.day.app/' + key + '/' + content)
    except Exception as e:
        print('Bark通知推送异常，原因为: ' + str(e))
        print(traceback.format_exc())

**Comment by Kelvinhou327** [comment]
这样可以吗 照着改的

**Comment by Kelvinhou327** [comment]
> 这样可以吗 照着改的

#发送Bark通知
def sendBark(key):
    try:
        key = Brak_Key
        #发送内容
        content = readFile_text('./log.txt')
        data = {
            'UnicomTask每日报表':content
        }
        content = urllib.parse.urlencode(data)
        requests.get('https://api.day.app/' + key + '/' + content)
    except Exception as e:
        print('Bark通知推送异常，原因为: ' + str(e))
        print(traceback.format_exc())

**Comment by srcrs** [comment]
@Kelvinhou327 这样很好啊，你可以模仿着其他的通知模块，添加到notify.py中，我看这已经写的差不多了。

**Comment by Kelvinhou327** [comment]
我跑了一下 没收到通知啊

**Comment by dh53128** [comment]
pushplus机器人的name怎么写呢？我填的pushplus没收到推送

**Comment by srcrs** [comment]
> pushplus机器人的name怎么写呢？我填的pushplus没收到推送

pushplus只需要填写token就可以了。

**Comment by dh53128** [comment]
> > pushplus机器人的name怎么写呢？我填的pushplus没收到推送
> 
> pushplus只需要填写token就可以了。
Name pushplus 
Value 123456 
是这样么？

**Comment by srcrs** [comment]
> > > pushplus机器人的name怎么写呢？我填的pushplus没收到推送
> > 
> > 
> > pushplus只需要填写token就可以了。
> > Name pushplus
> > Value 123456
> > 是这样么？

在最新的方式中，所有要填写的信息都参考config.json就行。

**Comment by Zoenzao** [comment]
感谢大佬们@Saxon-Sun  @srcrs
