### ISSUE TITLE
【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!

### ISSUE THREAD

**Issue by huangcaijj** [srcrs/UnicomTask#104]
【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!

这个问题怎么解决

**Comment by srcrs** [comment]
> 【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> 
> 这个问题怎么解决

填写appId

**Comment by huangcaijj** [comment]
o'k
