### ISSUE TITLE
账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by Axin608** [srcrs/UnicomTask#105]
账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)这是什么原因呀

**Comment by srcrs** [comment]
> 账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)这是什么原因呀

检查下添加的账号信息格式

**Comment by wsj199741** [comment]
我的也是这样，输入那个appid进去会自动换行

**Comment by wsj199741** [comment]
[](url)

> > 账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)这是什么原因呀
> 
> 检查下添加的账号信息格式

我的也是这样，输入那个appid进去会自动换行

**Comment by srcrs** [comment]
@wsj199741 @Axin608 建议填完后，在这个网站校验一下 https://www.bejson.com/

**Comment by srcrs** [comment]
> 我的也是这样，输入那个appid进去会自动换行

换行没有事，没有多余的字符就行

**Comment by wsj199741** [comment]
> > 我的也是这样，输入那个appid进去会自动换行
> 
> 换行没有事，没有多余的字符就行

[
![Uploading QQ截图20210305132117.png…]()
](url)

**Comment by wsj199741** [comment]
> > 我的也是这样，输入那个appId进去会自动换行
> 
> 换行没有事，没有多余的字符就行

哥，还是不行。都是直接复制粘贴的，逗号也删了

**Comment by srcrs** [comment]
> > > 我的也是这样，输入那个appId进去会自动换行
> > 
> > 
> > 换行没有事，没有多余的字符就行
> 
> 哥，还是不行。都是直接复制粘贴的，逗号也删了

填完后，运行新的工作流，可能是读取到旧的环境变量了

**Comment by wsj199741** [comment]
> > > > 我的也是这样，输入那个appId进去会自动换行
> > > 
> > > 
> > > 换行没有事，没有多余的字符就行
> > 
> > 
> > 哥，还是不行.都是直接复制粘贴的，逗号也删了
> 
> 填完后，运行新的工作流，可能是读取到旧的环境变量了

我都是删除fork重新操作一遍的，每次都是显示信息格式不对

**Comment by srcrs** [comment]
> > > > > 我的也是这样，输入那个appId进去会自动换行
> > > > 
> > > > 
> > > > 换行没有事，没有多余的字符就行
> > > 
> > > 
> > > 哥，还是不行.都是直接复制粘贴的，逗号也删了
> > 
> > 
> > 填完后，运行新的工作流，可能是读取到旧的环境变量了
> 
> 我都是删除fork重新操作一遍的，每次都是显示信息格式不对

截图给我看一下，你是不是添加的位置不对

**Comment by wsj199741** [comment]
> > > > > > 我的也是这样，输入那个appId进去会自动换行
> > > > > 
> > > > > 
> > > > > 换行没有事，没有多余的字符就行
> > > > 
> > > > 
> > > > 哥，还是不行.都是直接复制粘贴的，逗号也删了
> > > 
> > > 
> > > 填完后，运行新的工作流，可能是读取到旧的环境变量了
> > 
> > 
> > 我都是删除叉重新操作一遍的，每次都是显示信息格式不对
> 
> 截图给我看一下，你是不是添加的位置不对

![QQ截图20210305132117](https://user-images.githubusercontent.com/80032550/110074108-9f4e5780-7dbb-11eb-89e4-a76b04e85ca3.png)

**Comment by srcrs** [comment]
@wsj199741 名字叫做 USERS_COVER

**Comment by srcrs** [comment]
@wsj199741 注意看教程哈

**Comment by wsj199741** [comment]
> @wsj199741 名字叫做 USERS_COVER

额，没注意。因为都是用的网页翻译。看不懂。。

**Comment by wsj199741** [comment]
> @wsj199741 注意看教程哈

哥，你那个教程有误区,你打的xxx就几个，实际有很多字符，复制粘贴进去会换行，一直出错。
![QQ截图20210305145523](https://user-images.githubusercontent.com/80032550/110078567-e3912600-7dc2-11eb-84df-596ab4ab888b.png)

**Comment by srcrs** [comment]
> > @wsj199741 注意看教程哈
> 
> 哥，你那个教程有误区,你打的xxx就几个，实际有很多字符，复制粘贴进去会换行，一直出错。
> ![QQ截图20210305145523](https://user-images.githubusercontent.com/80032550/110078567-e3912600-7dc2-11eb-84df-596ab4ab888b.png)

你在这里吧json调成不换行，就ok了。那里换行是没办法，它装不下，实际上还是一行。

**Comment by srcrs** [comment]
> > > @wsj199741 注意看教程哈
> > 
> > 
> > 哥，你那个教程有误区,你打的xxx就几个，实际有很多字符，复制粘贴进去会换行，一直出错。
> > ![QQ截图20210305145523](https://user-images.githubusercontent.com/80032550/110078567-e3912600-7dc2-11eb-84df-596ab4ab888b.png)
> 
> 你在这里吧json调成不换行，就ok了。那里换行是没办法，它装不下，实际上还是一行。

不可能说那么多人都可以用，到这里就不行了的。

> > > @wsj199741 注意看教程哈
> > 
> > 
> > 哥，你那个教程有误区,你打的xxx就几个，实际有很多字符，复制粘贴进去会换行，一直出错。
> > ![QQ截图20210305145523](https://user-images.githubusercontent.com/80032550/110078567-e3912600-7dc2-11eb-84df-596ab4ab888b.png)
> 
> 你在这里吧json调成不换行，就ok了。那里换行是没办法，它装不下，实际上还是一行。

你在这里把格式调整对，就好了。再不行，你把微信号发到我的邮箱 srcrs@foxmail.com，咱们细聊。

**Comment by Axin608** [comment]
检查运行的时候是对的，但是到测试云函数就错，微信发你，教教我老哥
