### ISSUE TITLE
进行一次push操作报错

### ISSUE THREAD

**Issue by 1534731303** [srcrs/UnicomTask#116]
##***group***Run echo "$USERS_COVER" > ./config.json
***36;1mecho "$USERS_COVER" > ./config.json***0m
***36;1mpython main.py***0m
shell: /usr/bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
  USERS_COVER: ***

##***endgroup***
***2021-03-07 12:20:41,092***:ERROR:账号信息格式填写错误，原因为: Expecting ',' delimiter: line 12 column 1 (char 428)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 336, in readJson
    users = json.load(fp)
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 377, in <module>
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 1 (char 428)

    main("","")
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 345, in main
    for user in users:
TypeError: 'NoneType' object is not iterable
##***error***Process completed with exit code 1.

**Comment by srcrs** [comment]
> ##_**group**_Run echo "$USERS_COVER" > ./config.json
> �_**36;1mecho "$USERS_COVER" > ./config.json�**_0m
> �_**36;1mpython main.py�**_0m
> shell: /usr/bin/bash -e _**0**_
> env:
> pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
> LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
> USERS_COVER: ***
> 
> ##_**endgroup**_
> _**2021-03-07 12:20:41,092**_:ERROR:账号信息格式填写错误，原因为: Expecting ',' delimiter: line 12 column 1 (char 428)
> Traceback (most recent call last):
> Traceback (most recent call last):
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 336, in readJson
> users = json.load(fp)
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 377, in
> File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/**init**.py", line 293, in load
> return loads(fp.read(),
> File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/**init**.py", line 346, in loads
> return _default_decoder.decode(s)
> File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 353, in raw_decode
> obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 1 (char 428)
> 
> ```
> main("","")
> ```
> 
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 345, in main
> for user in users:
> TypeError: 'NoneType' object is not iterable
> ##_**error**_Process completed with exit code 1.

检查下secrets添加的位置、格式、命令等信息。
