### ISSUE TITLE
账号信息格式填写错误 Expecting value: line 2 column 1

### ISSUE THREAD

**Issue by ChewJ404** [srcrs/UnicomTask#118]
```bash
[2021-03-08 02:31:54,684]:ERROR:账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 336, in readJson
    users = json.load(fp)
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

---------------------------------------------------------------------
请问 下如何 解决  up,.,感觉 config.json  也没有配置错误 config.json如下 ,**部分敏感数据已进行替换** , 谢谢解答
```bash
[
    {
        "username": "18672000000",
        "password": "300007",
        "appId": "d519d15e931bde36c60f4b36xxxxxxxfdcb3a48a20e90c32fa5d913a449e6381fe11d3238f3929d0e4ce9bd76873dff444b897f5019069c3bbf2365d0f0eaf60c744573db4d3775633c73f315255fa72239",
        "email": "755555555@qq.com",
        "lotteryNum": "1",
        "dingtalkWebhook": "https://oapi.dingtalk.com/robot/send?access_token=b1ad2xxxxxx9cee2398512110fd251"
    }
]
```

**Comment by ChewJ404** [comment]
google 了下  网上说  可能是

JSON数据中数据存在多行，在读取数据时，不能够单单用open()，应利用for循环：
```python
json_data=[]

for line in open('多列表.json', 'r', encoding='utf-8'):

json_data.append(line)
```

**Comment by srcrs** [comment]
> google 了下 网上说 可能是 如下原因 , up 看下呗
> 
> JSON数据中数据存在多行，在读取数据时，不能够单单用open()，应利用for循环：
> 
> ```python
> file = open("config.json", 'r', encoding='utf-8')
> papers = []
> for line in file.readlines():
>     dic = json.loads(line)
>     papers.append(dic)
> ```

不会吧，我也是有很多行的，截图我看一下你添加的secrets，是不是位置错了

**Comment by linyi81953221** [comment]
USERS_COVER是不是这个设置错了

**Comment by linyi81953221** [comment]
我之前写成了USERNAME_COVER  也这样报错

**Comment by ChewJ404** [comment]
@srcrs @linyi81953221 
```python
Repository secrets

APPID_COVER                     
EMAIL_COVER                     
LOTTERY_NUM                    
PASSWORD_COVER            
USERNAME_COVER            
```
请问下   secrets 里面 是 两周前弄的 ,当时 就可以用,成功了, 最近是 看到 有个config.json 可以配置 钉钉 hook 然后就在 config 里面也配了, 现在就是  报 上面那个问题

**Comment by linyi81953221** [comment]
我之前写成了USERNAME_COVER&nbsp; 改成USERS_COVER就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aaak"<notifications@github.com&gt;; 
发送时间: 2021年3月9日(星期二) 中午1:24
收件人: "srcrs/UnicomTask"<UnicomTask@noreply.github.com&gt;; 
抄送: "504781494"<504781494@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [srcrs/UnicomTask] 账号信息格式填写错误 Expecting value: line 2 column 1 (#118)





 
@srcrs @linyi81953221
 Repository secrets APPID_COVER                      EMAIL_COVER                      LOTTERY_NUM                     PASSWORD_COVER             USERNAME_COVER            
 
请问下   secrets 里面 是 两周前弄的 ,当时 就可以用,成功了, 最近是 看到 有个config.json 可以配置 钉钉 hook 然后就在 config 里面也配了, 现在就是  报 上面那个问题

**Comment by iuaries** [comment]
![image](https://user-images.githubusercontent.com/62986244/110743304-ccdf4900-8272-11eb-9627-144651bcaaef.png)
这是啥原因啊

**Comment by ChewJ404** [comment]
@iuaries  secrets 设置的  `USERNAME_COVER` 的值  json 不对 或者格式有问题

**Comment by srcrs** [comment]
> > @iuaries secrets 设置的 `USERNAME_COVER` 的值 json 不对 或者格式有问题
> 
> 我在网站验证过json格式的正确性后，还是不行，结果跟图中一样。要填的appid是unicom/appid文件里面所有的内容是吗？

是的

**Comment by iuaries** [comment]
> > > @iuaries secrets 设置的 `USERNAME_COVER` 的值 json 不对 或者格式有问题
> > 
> > 
> > 我在网站验证过json格式的正确性后，还是不行，结果跟图中一样。要填的appid是unicom/appid文件里面所有的内容是吗？
> 
> 是的

但是最后还是失败了
![image](https://user-images.githubusercontent.com/62986244/110751505-d6998a00-823b-11eb-8698-1a0d29af5318.png)

**Comment by ChewJ404** [comment]
> > > > @iuaries secrets 设置的 `USERNAME_COVER` 的值 json 不对 或者格式有问题
> > > 
> > > 
> > > 我在网站验证过json格式的正确性后，还是不行，结果跟图中一样。要填的appid是unicom/appid文件里面所有的内容是吗？
> > 
> > 
> > 是的
> 
> 但是最后还是失败了
> ![image](https://user-images.githubusercontent.com/62986244/110751505-d6998a00-823b-11eb-8698-1a0d29af5318.png)

你截图 图片 内已经有提示了 ,是否 账户信息之类的 不对, 反正我 `secrets` 添加了如下这些
`APPID_COVER`
`EMAIL_COVER `
`LOTTERY_NUM `
`PASSWORD_COVER `
`USERNAME_COVER`
`USERS_COVER`

**Comment by iuaries** [comment]
> > > > > @iuaries secrets 设置的 `USERNAME_COVER` 的值 json 不对 或者格式有问题
> > > > 
> > > > 
> > > > 我在网站验证过json格式的正确性后，还是不行，结果跟图中一样。要填的appid是unicom/appid文件里面所有的内容是吗？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 但是最后还是失败了
> > ![image](https://user-images.githubusercontent.com/62986244/110751505-d6998a00-823b-11eb-8698-1a0d29af5318.png)
> 
> 你截图 图片 内已经有提示了 ,是否 账户信息之类的 不对, 反正我 `secrets` 添加了如下这些
> `APPID_COVER`
> `EMAIL_COVER `
> `LOTTERY_NUM `
> `PASSWORD_COVER `
> `USERNAME_COVER`
> `USERS_COVER`

![image](https://user-images.githubusercontent.com/62986244/110752895-cfe13600-8280-11eb-9862-5bec6e2f9346.png)
![image](https://user-images.githubusercontent.com/62986244/110752907-d2439000-8280-11eb-9ae4-28278e62563f.png)
要一个一个单独在secrets里面添加吗？
