### ISSUE TITLE
有没有腾讯云函数具体使用办法呀

### ISSUE THREAD

**Issue by 2757227663** [srcrs/UnicomTask#120]
有没有腾讯云函数具体使用办法呀，这里提供的方法太简洁了，能不能提供一个云函数部署的图文教程

**Comment by srcrs** [comment]
> 有没有腾讯云函数具体使用办法呀，这里提供的方法太简洁了，能不能提供一个云函数部署的图文教程

教程已经很清楚了，就只需要找相应的腾讯云环境变量即可。

**Comment by JohnED512** [comment]
现在云函数部署时间特别长

**Comment by srcrs** [comment]
> 现在云函数部署时间特别长

貌似出现点问题，我这边部署不上云函数了

**Comment by JohnED512** [comment]
> > 现在云函数部署时间特别长
> 
> 貌似出现点问题，我这边部署不上云函数了

我也是，Actions执行完了看云函数里没有

**Comment by srcrs** [comment]
> > > 现在云函数部署时间特别长
> > 
> > 
> > 貌似出现点问题，我这边部署不上云函数了
> 
> 我也是，Actions执行完了看云函数里没有

不知道是不是开会原因，把Github的ip给断了

**Comment by srcrs** [comment]
> > > > 现在云函数部署时间特别长
> > > 
> > > 
> > > 貌似出现点问题，我这边部署不上云函数了
> > 
> > 
> > 我也是，Actions执行完了看云函数里没有
> 
> 不知道是不是开会原因，把Github的ip给断了

今天凌晨的时候我边还是可以的。
