### ISSUE TITLE
自动兑换临期流量包

### ISSUE THREAD

**Issue by AielloChan** [srcrs/UnicomTask#124]
可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉

**Comment by uclinch** [comment]
同求 毕竟每日1G的流量包只有4天还是5天有效期，很短，基本上不可能当存货，还不如每日自动使用。

**Comment by linyi81953221** [comment]
同求  最好自动领取礼包，要不每天还要想着领取

**Comment by AielloChan** [comment]
> 可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉

抓包看了一下，很好搞。

策略可以商量统一一下，比如到期日期是当天的，就全部自动兑换使用，不论是日包、月包（毕竟第二天都过期了）

**Comment by srcrs** [comment]
> > 可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉
> 
> 抓包看了一下，很好搞。
> 
> 策略可以商量统一一下，比如到期日期是当天的，就全部自动兑换使用，不论是日包、月包（毕竟第二天都过期了）

可以，流量包确实可以自动去使用，过期了就得不偿失了。可是近期比较忙，你们有会弄得，可以一起搞一下。
流量包返回的不是Json，而是一个网页，数据筛选方面要复杂些。

**Comment by srcrs** [comment]
> > 可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉
> 
> 抓包看了一下，很好搞。
> 
> 策略可以商量统一一下，比如到期日期是当天的，就全部自动兑换使用，不论是日包、月包（毕竟第二天都过期了）

请求支援一下，我这边遇到点问题，什么都做好了（找到流量包-》判断即将过期流量包-》激活流量包），就是流量包激活不了。

**Comment by AielloChan** [comment]
> > > 可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉
> > 
> > 
> > 抓包看了一下，很好搞。
> > 策略可以商量统一一下，比如到期日期是当天的，就全部自动兑换使用，不论是日包、月包（毕竟第二天都过期了）
> 
> 请求支援一下，我这边遇到点问题，什么都做好了（找到流量包-》判断即将过期流量包-》激活流量包），就是流量包激活不了。

我也在做哈哈，正想上来问“可以引入 HTML 选择器不”，就看到了。“激活不了”这个，是什么一个表现呢？

**Comment by srcrs** [comment]
> > > > 可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉
> > > 
> > > 
> > > 抓包看了一下，很好搞。
> > > 策略可以商量统一一下，比如到期日期是当天的，就全部自动兑换使用，不论是日包、月包（毕竟第二天都过期了）
> > 
> > 
> > 请求支援一下，我这边遇到点问题，什么都做好了（找到流量包-》判断即将过期流量包-》激活流量包），就是流量包激活不了。
> 
> 我也在做哈哈，正想上来问“可以引入 HTML 选择器不”，就看到了。“激活不了”这个，是什么一个表现呢？

情况是这样，这个接口可能是激活流量包的接口`http://m.client.10010.com/myPrizeForActivity/myPrize/activationFlowPackages.htm`，我携带的流量包的参数发送请求，返回的200，与抓包情况一样，但实际上该流量包并没有激活

**Comment by AielloChan** [comment]
> > > > > 可否支持自动兑换临近到期的流量日包。issue 提在这里，空了我也可以研究一下😉
> > > > 
> > > > 
> > > > 抓包看了一下，很好搞。
> > > > 策略可以商量统一一下，比如到期日期是当天的，就全部自动兑换使用，不论是日包、月包（毕竟第二天都过期了）
> > > 
> > > 
> > > 请求支援一下，我这边遇到点问题，什么都做好了（找到流量包-》判断即将过期流量包-》激活流量包），就是流量包激活不了。
> > 
> > 
> > 我也在做哈哈，正想上来问“可以引入 HTML 选择器不”，就看到了。“激活不了”这个，是什么一个表现呢？
> 
> 情况是这样，这个接口可能是激活流量包的接口`http://m.client.10010.com/myPrizeForActivity/myPrize/activationFlowPackages.htm`，我携带的流量包的参数发送请求，返回的200，与抓包情况一样，但实际上该流量包并没有激活

```python
data = {
    'activeCode': 2534,
    'prizeRecordID': 20210307074049XXXXXXXXX389,
    'activeName': '做任务领奖品',
}
page = client.post('http://m.client.10010.com/myPrizeForActivity/myPrize/activationFlowPackages.htm', data=data)
page.encoding='utf-8'
```

实测，把我仅剩的一个包给激活了，可行的

**Comment by srcrs** [comment]
@AielloChan 是使用代码的吗？

**Comment by AielloChan** [comment]
嗯，就上面就是 python 代码，只是我把我的 prizeRecordID 打码了😹

**Comment by srcrs** [comment]
> 嗯，就上面就是 python 代码，只是我把我的 prizeRecordID 打码了😹

我与你的区别是，上面的那两个值是字符串，我这边改成你那样试试

**Comment by srcrs** [comment]
> > 嗯，就上面就是 python 代码，只是我把我的 prizeRecordID 打码了😹
> 
> 我与你的区别是，上面的那两个值是字符串，我这边改成你那样试试

可算是激活成功一次

**Comment by AielloChan** [comment]
> > > 嗯，就上面就是 python 代码，只是我把我的 prizeRecordID 打码了😹
> > 
> > 
> > 我与你的区别是，上面的那两个值是字符串，我这边改成你那样试试
> 
> 可算是激活成功一次

嗯，在解析流量包的那个页面，你是直接用的正则还是用了 HTML Selector 库呢？

**Comment by srcrs** [comment]
> > > > 嗯，就上面就是 python 代码，只是我把我的 prizeRecordID 打码了😹
> > > 
> > > 
> > > 我与你的区别是，上面的那两个值是字符串，我这边改成你那样试试
> > 
> > 
> > 可算是激活成功一次
> 
> 嗯，在解析流量包的那个页面，你是直接用的正则还是用了 HTML Selector 库呢？

用的这个lxml，xpath解析器

**Comment by srcrs** [comment]
> > 嗯，就上面就是 python 代码，只是我把我的 prizeRecordID 打码了😹
> 
> 我与你的区别是，上面的那两个值是字符串，我这边改成你那样试试

实测，就是引号的锅。

**Comment by srcrs** [comment]
@AielloChan 原因在我 `toDetailPage('2534','20210307073111185674422127348889','18566669999')`   这里应该去掉头和尾的单引号，我错当成了，字符串。

**Comment by srcrs** [comment]
> @AielloChan 原因在我 `toDetailPage('2534','20210307073111185674422127348889','18566669999')` 这里应该去掉头和尾的单引号，我错当成了，字符串。

那边后端也不给个提示我，错误了什么的。

**Comment by AielloChan** [comment]
> > @AielloChan 原因在我 `toDetailPage('2534','20210307073111185674422127348889','18566669999')` 这里应该去掉头和尾的单引号，我错当成了，字符串。
> 
> 那边后端也不给个提示我，错误了什么的。

哈哈，可以了就行，这个功能一上，每天的流量就不愁了。我在研究那个玩游戏奖励 3G 流量的东西了

**Comment by AielloChan** [comment]
粗略抓了下包，看起来联通客户端就是一个壳，然后接的腾讯的小游戏平台，由腾讯负责统计游戏时间。然后联通客户端这边轮训游戏时长，符合条件就开放兑换接口调用。腾讯每条信息里面都二次加密（非文本或者加签名字段），目测希望不大 😂

**Comment by srcrs** [comment]
> 粗略抓了下包，看起来联通客户端就是一个壳，然后接的腾讯的小游戏平台，由腾讯负责统计游戏时间。然后联通客户端这边轮训游戏时长，符合条件就开放兑换接口调用。腾讯每条信息里面都二次加密（非文本或者加签名字段），目测希望不大 😂

你那边还有网，我这边直接进不去😂

**Comment by srcrs** [comment]
> 粗略抓了下包，看起来联通客户端就是一个壳，然后接的腾讯的小游戏平台，由腾讯负责统计游戏时间。然后联通客户端这边轮训游戏时长，符合条件就开放兑换接口调用。腾讯每条信息里面都二次加密（非文本或者加签名字段），目测希望不大 😂

游戏中心签到总是出现接口防刷，老哥没事给研究研究呗。

**Comment by Ahorace** [comment]
@srcrs 我三个号码同时使用自动激活临期流量包，只有最后一个激活了流量包，前两个未激活流量包，不清楚是什么问题

**Comment by srcrs** [comment]
> @srcrs 我三个号码同时使用自动激活临期流量包，只有最后一个激活了流量包，前两个未激活流量包，不清楚是什么问题

你好，我看了下你的日志文件，显示是正常的。本项目只会帮你激活即将过期的流量包，也就是到期时间为1天之内。

**Comment by bugme2** [comment]
> 粗略抓了下包，看起来联通客户端就是一个壳，然后接的腾讯的小游戏平台，由腾讯负责统计游戏时间。然后联通客户端这边轮训游戏时长，符合条件就开放兑换接口调用。腾讯每条信息里面都二次加密（非文本或者加签名字段），目测希望不大 😂

那为什么以前那个AutoSignMachine项目可以做到呢

**Comment by histion** [comment]
> @All 已添加自动激活即将过期流量包功能

测试了一下。今天到期的包没有激活，不知道什么情况

**Comment by AielloChan** [comment]
> > 粗略抓了下包，看起来联通客户端就是一个壳，然后接的腾讯的小游戏平台，由腾讯负责统计游戏时间。然后联通客户端这边轮训游戏时长，符合条件就开放兑换接口调用。腾讯每条信息里面都二次加密（非文本或者加签名字段），目测希望不大 😂
> 
> 那为什么以前那个AutoSignMachine项目可以做到呢

去看了源码，那个哥们儿挺厉害，加密的密钥都有，那看来要实现的话问题也不大了（如果那个密钥还有效的话）

**Comment by AielloChan** [comment]
> > @ALL 已添加自动激活即将过期流量包功能
> 
> 测试了一下。今天到期的包没有激活，不知道什么情况

拉一下最新的代码，代码里面更新了时区计算，之前有可能在过期时间的计算上有问题。主动去触发一下那个auto_merge workflow，会自动更新代码；然后再主动触发一下 Unicom_Task 那个 workflow，跑一遍脚本。

**Comment by bugme2** [comment]
> > > 粗略抓了下包，看起来联通客户端就是一个壳，然后接的腾讯的小游戏平台，由腾讯负责统计游戏时间。然后联通客户端这边轮训游戏时长，符合条件就开放兑换接口调用。腾讯每条信息里面都二次加密（非文本或者加签名字段），目测希望不大 😂
> > 
> > 
> > 那为什么以前那个AutoSignMachine项目可以做到呢
> 
> 去看了源码，那个哥们儿挺厉害，加密的密钥都有，那看来要实现的话问题也不大了（如果那个密钥还有效的话）

能用，那个项目还有很多奖励积分，这个项目只有一个签到积分，可惜那个项目删库跑路了
