### ISSUE TITLE
建议更新推送加推送接口

### ISSUE THREAD

**Issue by wind0ws** [srcrs/UnicomTask#134]
pushplus.hxtrip.com 已经发了相关通知，4月份前后即将关闭 pushplus.hxtrip.com 接口的推送
文章链接：  https://mp.weixin.qq.com/s/XbWih4Mv5ggBPGg0-QBJJw

建议将 pushplus.hxtrip.com 域名改为 www.pushplus.plus 以便后续能继续使用推送加的服务，
并提醒用户在www.pushplus.plus上申请新token

**Comment by srcrs** [comment]
> pushplus.hxtrip.com 已经发了相关通知，4月份前后即将关闭 pushplus.hxtrip.com 接口的推送
> 文章链接： https://mp.weixin.qq.com/s/XbWih4Mv5ggBPGg0-QBJJw
> 
> 建议将 pushplus.hxtrip.com 域名改为 [www.pushplus.plus](http://www.pushplus.plus) 以便后续能继续使用推送加的服务，
> 并提醒用户在www.pushplus.plus上申请新token

收到，感谢。
