### ISSUE TITLE
云函数出错

### ISSUE THREAD

**Issue by alanng2017** [srcrs/UnicomTask#137]
{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/main.py\", line 7, in \u003cmodule\u003e\n    from lxml import etree\nImportError: cannot import name 'etree'","statusCode":443}

**Comment by srcrs** [comment]
> {"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n File "/var/runtime/python3/bootstrap.py", line 133, in init_handler\n func_handler = get_func_handler(file.rsplit(".", 1)[0], func)\n File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler\n mod = imp.load_module(mname, *imp.find_module(mname))\n File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module\n return load_source(name, filename, file)\n File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source\n module = _load(spec)\n File "\u003cfrozen importlib._bootstrap\u003e", line 675, in _load\n File "\u003cfrozen importlib._bootstrap\u003e", line 655, in _load_unlocked\n File "\u003cfrozen importlib._bootstrap_external\u003e", line 678, in exec_module\n File "\u003cfrozen importlib._bootstrap\u003e", line 205, in _call_with_frames_removed\n File "/var/user/main.py", line 7, in \u003cmodule\u003e\n from lxml import etree\nImportError: cannot import name 'etree'","statusCode":443}

这个是由于lxml模块中etree未找到问题，稍后降低lxml版本应该可解决问题。

**Comment by YujiaCheng1996** [comment]
手动部署时也有这个问题，lxml为4.6.2

**Comment by srcrs** [comment]
@alanng2017 

> 手动部署时也有这个问题，lxml为4.6.2

云函数python版本为3.6会出现这个问题，但是我在本地和actions都是3.9不会出现这个问题。在云函数中手动部署，把lxml版本调整为4.2.5试一下，应该可解决。

**Comment by srcrs** [comment]
> @alanng2017
> 
> > 手动部署时也有这个问题，lxml为4.6.2
> 
> 云函数python版本为3.6会出现这个问题，但是我在本地和actions都是3.9不会出现这个问题。在云函数中手动部署，把lxml版本调整为4.2.5试一下，应该可解决。

但4.2.5在action又会报错

**Comment by lnterface** [comment]
亲测4.2.5也不行，换到4.0.0可以了

**Comment by srcrs** [comment]
> 亲测4.2.5也不行，换到4.0.0可以了

4.0.0在action和云函数都能运行吗？

**Comment by Ynooo** [comment]
> > 亲测4.2.5也不行，换到4.0.0可以了
> 
> 4.0.0在action和云函数都能运行吗？

最新更新的也出现这个问题，大佬怎么调整？

**Comment by srcrs** [comment]
> > > 亲测4.2.5也不行，换到4.0.0可以了
> > 
> > 
> > 4.0.0在action和云函数都能运行吗？
> 
> 最新更新的也出现这个问题，大佬怎么调整？

不行把lxml模块换掉吧，Actions和本地都可运行，不太清楚是什么原因导致的etree模块找不到。

**Comment by srcrs** [comment]
@All  大家试一下云函数版本好了没有

**Comment by davidelectricfree** [comment]
> 
> 
> @ALL 大家试一下云函数版本好了没有

还不行

**Comment by lnterface** [comment]
> > 亲测4.2.5也不行，换到4.0.0可以了
> 
> 4.0.0在action和云函数都能运行吗？

没用action不太清楚，但是云函数是没问题的

**Comment by davidelectricfree** [comment]
> 
> 
> > > 亲测4.2.5也不行，换到4.0.0可以了
> > 
> > 
> > 4.0.0在action和云函数都能运行吗？
> 
> 没用action不太清楚，但是云函数是没问题的

单单改成4.0.0不好用好像，最新的版本把lxml直接上传到云函数那边本地部署就挺好。

**Comment by caiop11** [comment]
云函数部署成功
