### ISSUE TITLE
报错 建立和发布

### ISSUE THREAD

**Issue by shiguang5200** [srcrs/UnicomTask#141]
##***group***Run echo "$USERS_COVER" > ./config.json
***36;1mecho "$USERS_COVER" > ./config.json***0m
***36;1mpython main.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
  USERS_COVER: ***
##***endgroup***
***2021-03-10 05:06:47,916***:INFO:【登录】: 3510
***2021-03-10 05:06:49,325***:INFO:【积分余额】: 426
***2021-03-10 05:06:57,521***:INFO:【每日签到】: 打卡成功,翻倍成功
***2021-03-10 05:07:00,090***:INFO:【1G流量日包】: 领取成功
***2021-03-10 05:07:03,325***:INFO:【天天抽奖】: 谢谢参与~ x1
***2021-03-10 05:07:04,767***:INFO:【天天抽奖】: 谢谢参与~ x2
***2021-03-10 05:07:06,185***:INFO:【天天抽奖】: 2MB x3
***2021-03-10 05:07:07,998***:INFO:【积分抽奖】: 5MB流量 x免费
***2021-03-10 05:07:08,940***:INFO:【100定向积分】: 领取成功
***2021-03-10 05:07:11,459***:INFO:【东奥积分活动】: 领取成功，600积分
***2021-03-10 05:07:15,220***:INFO:【游戏中心签到】: 获得1积分
***2021-03-10 05:07:16,605***:INFO:【游戏频道打卡】: 获得1积分
***2021-03-10 05:07:22,278***:INFO:【100M寻宝箱】: 获得100M流量
***2021-03-10 05:07:24,889***:INFO:【4G流量包-看视频】: 获得30M流量 x1
***2021-03-10 05:07:26,272***:INFO:【4G流量包-下软件】: 获得50M流量 x1
***2021-03-10 05:07:27,741***:INFO:【4G流量包-看视频】: 获得30M流量 x2
***2021-03-10 05:07:29,242***:INFO:【4G流量包-下软件】: 获得50M流量 x2
***2021-03-10 05:07:32,446***:INFO:【4G流量包-看视频】: 获得30M流量 x3
***2021-03-10 05:07:33,828***:INFO:【4G流量包-下软件】: 获得50M流量 x3
***2021-03-10 05:07:36,077***:INFO:【沃之树-领流量】: 4M流量 x1
***2021-03-10 05:07:37,447***:INFO:【沃之树-领流量】: 4M流量 x2
***2021-03-10 05:07:38,813***:INFO:【沃之树-领流量】: 4M流量 x3
***2021-03-10 05:07:40,884***:INFO:【沃之树-浇水】: 获得3培养值
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 491, in <module>
    main("","")
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 477, in main
    actionFlow(user***'username'***)
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 426, in actionFlow
    endTime = getflowEndTime(username)
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 410, in getflowEndTime
    index = end.find('-')+1
AttributeError: 'NoneType' object has no attribute 'find'
##***error***Process completed with exit code 1.

**Comment by srcrs** [comment]
> ##_**group**_Run echo "$USERS_COVER" > ./config.json
> �_**36;1mecho "$USERS_COVER" > ./config.json�**_0m
> �_**36;1mpython main.py�**_0m
> shell: /bin/bash -e _**0**_
> env:
> pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
> LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
> USERS_COVER: ***
> ##_**endgroup**_
> _**2021-03-10 05:06:47,916**_:INFO:【登录】: 3510
> _**2021-03-10 05:06:49,325**_:INFO:【积分余额】: 426
> _**2021-03-10 05:06:57,521**_:INFO:【每日签到】: 打卡成功,翻倍成功
> _**2021-03-10 05:07:00,090**_:INFO:【1G流量日包】: 领取成功
> _**2021-03-10 05:07:03,325**_:INFO:【天天抽奖】: 谢谢参与~ x1
> _**2021-03-10 05:07:04,767**_:INFO:【天天抽奖】: 谢谢参与~ x2
> _**2021-03-10 05:07:06,185**_:INFO:【天天抽奖】: 2MB x3
> _**2021-03-10 05:07:07,998**_:INFO:【积分抽奖】: 5MB流量 x免费
> _**2021-03-10 05:07:08,940**_:INFO:【100定向积分】: 领取成功
> _**2021-03-10 05:07:11,459**_:INFO:【东奥积分活动】: 领取成功，600积分
> _**2021-03-10 05:07:15,220**_:INFO:【游戏中心签到】: 获得1积分
> _**2021-03-10 05:07:16,605**_:INFO:【游戏频道打卡】: 获得1积分
> _**2021-03-10 05:07:22,278**_:INFO:【100M寻宝箱】: 获得100M流量
> _**2021-03-10 05:07:24,889**_:INFO:【4G流量包-看视频】: 获得30M流量 x1
> _**2021-03-10 05:07:26,272**_:INFO:【4G流量包-下软件】: 获得50M流量 x1
> _**2021-03-10 05:07:27,741**_:INFO:【4G流量包-看视频】: 获得30M流量 x2
> _**2021-03-10 05:07:29,242**_:INFO:【4G流量包-下软件】: 获得50M流量 x2
> _**2021-03-10 05:07:32,446**_:INFO:【4G流量包-看视频】: 获得30M流量 x3
> _**2021-03-10 05:07:33,828**_:INFO:【4G流量包-下软件】: 获得50M流量 x3
> _**2021-03-10 05:07:36,077**_:INFO:【沃之树-领流量】: 4M流量 x1
> _**2021-03-10 05:07:37,447**_:INFO:【沃之树-领流量】: 4M流量 x2
> _**2021-03-10 05:07:38,813**_:INFO:【沃之树-领流量】: 4M流量 x3
> _**2021-03-10 05:07:40,884**_:INFO:【沃之树-浇水】: 获得3培养值
> Traceback (most recent call last):
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 491, in
> main("","")
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 477, in main
> actionFlow(user***'username'***)
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 426, in actionFlow
> endTime = getflowEndTime(username)
> File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 410, in getflowEndTime
> index = end.find('-')+1
> AttributeError: 'NoneType' object has no attribute 'find'
> ##_**error**_Process completed with exit code 1.

这个是由于流量包到期时间获取失败错误，你再重新运行下试试。

**Comment by srcrs** [comment]
@shiguang5200 你的流量包是否没有到期时间？

**Comment by srcrs** [comment]
@shiguang5200 你是不是又永久的流量包？

**Comment by shiguang5200** [comment]
确实有几个还没到激活时间的流量包，另重新运行依旧同样报错，感谢解答

**Comment by srcrs** [comment]
> 确实有几个还没到激活时间的流量包，另重新运行依旧同样报错，感谢解答

好的，我明白了。马上修复。

**Comment by shiguang5200** [comment]
主套餐是限速不限量的永久包，礼包里的赠送礼包都有明确的到期时间

**Comment by srcrs** [comment]
> 主套餐是限速不限量的永久包，礼包里的赠送礼包都有明确的到期时间

是否有那种，未到开启时间的，你看一下时间是否都是这种形式的
![4d9370f6a859444ff10697b671b2168](https://user-images.githubusercontent.com/49332985/110584253-e2d50700-81a9-11eb-9e0d-2543299b78be.png)

**Comment by srcrs** [comment]
@shiguang5200 更新下代码

**Comment by bearcony** [comment]
云函数最新部署出错，无法部署。
![Screenshot_20210310-143520~2](https://user-images.githubusercontent.com/56168806/110587017-04d08880-81ae-11eb-9d70-2e1c0fad0075.jpg)

**Comment by davidelectricfree** [comment]
> 
> 
> 云函数最新部署出错，无法部署。
> ![Screenshot_20210310-143520~2](https://user-images.githubusercontent.com/56168806/110587017-04d08880-81ae-11eb-9d70-2e1c0fad0075.jpg)
一样的问题，我看了一下其他人的action log（比如说:https://github.com/srcrs/UnicomTask/runs/2076391303?check_suite_focus=true） 也是一样的。

**Comment by davidelectricfree** [comment]
> 
> 
> 云函数最新部署出错，无法部署。
> ![Screenshot_20210310-143520~2](https://user-images.githubusercontent.com/56168806/110587017-04d08880-81ae-11eb-9d70-2e1c0fad0075.jpg)

一样的问题，我看了一下其他人的action log（https://github.com/srcrs/UnicomTask/runs/2076391303?check_suite_focus=true），也存在一样的问题。

**Comment by davidelectricfree** [comment]
> 
> 
> > > 云函数最新部署出错，无法部署。
> > > ![Screenshot_20210310-143520~2](https://user-images.githubusercontent.com/56168806/110587017-04d08880-81ae-11eb-9d70-2e1c0fad0075.jpg)
> > 
> > 
> > 一样的问题，我看了一下其他人的action log（[https://github.com/srcrs/UnicomTask/runs/2076391303?check_suite_focus=true），](https://github.com/srcrs/UnicomTask/runs/2076391303?check_suite_focus=true%EF%BC%89%EF%BC%8C) 也存在一样的问题。
> 
> 现在应该好了吧，我这边正常了的。

Error: Request failed with status code 400
好像还不行

**Comment by bearcony** [comment]
我是看别人改成4.0版本就行了，我也改了部署了。

**Comment by srcrs** [comment]
> > 我是看别人改成4.0版本就行了，我也改了部署了。
> 
> 我没改，刚刚试一下又好了，可能和最近的网络环境有关吧，最近网络不太稳定 @srcrs

是的，应该不会跟添加了lxml包又关联吧
