### ISSUE TITLE
提示让使用短信验证码登录的问题，怎么解决呢

### ISSUE THREAD

**Issue by an0na** [srcrs/UnicomTask#145]
##***group***Run echo "$USERS_COVER" > ./config.json
***36;1mecho "$USERS_COVER" > ./config.json***0m
***36;1mpython main.py***0m
shell: /usr/bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
  USERS_COVER: ***
##***endgroup***
***2021-03-10 08:49:27,818***:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
<Response ***200***>

**Comment by srcrs** [comment]
appid没填写，或者不正确。
