### ISSUE TITLE
INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!

### ISSUE THREAD

**Issue by cairnechen** [srcrs/UnicomTask#154]
按照引导设置好了，push触发了一次，营业厅查看任务都没有做，workflow记录发现这个提示，是我哪个步骤错了吗？

**Comment by stunum** [comment]
我也遇到同样的问题了

**Comment by SLCSLC** [comment]
用初始服务密码会出现这种情况，自己改一下服务密码就好了

**Comment by coderbean** [comment]
我是抓包deviceid错了，抓出来的包里面有两个不同的deviceid，是长的那个

**Comment by thomas502** [comment]
我的也是这问题  我的不是初始密码  在别的脚本上运行顺利

**Comment by srcrs** [comment]
> 按照引导设置好了，push触发了一次，营业厅查看任务都没有做，workflow记录发现这个提示，是我哪个步骤错了吗？

通常，appId不对
