### ISSUE TITLE
requirements.txt 没更新呀

### ISSUE THREAD

**Issue by yzbwork** [srcrs/UnicomTask#156]
requirements.txt

**Comment by srcrs** [comment]
> requirements.txt

这个不需要更新，之前云函数错误是由于环境问题，我把能用的lxml源码拷贝了一份。

**Comment by yzbwork** [comment]
> > requirements.txt
> 
> 这个不需要更新，之前云函数错误是由于环境问题，我把能用的lxml源码拷贝了一份。
这个action失败了
##***group***Run echo "$USERS_COVER" > ./config.json
***36;1mecho "$USERS_COVER" > ./config.json***0m
***36;1mpython main.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
  USERS_COVER: ***
##***endgroup***
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 8, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
##***error***Process completed with exit code 1.

**Comment by srcrs** [comment]
> > > requirements.txt
> > 
> > 
> > 这个不需要更新，之前云函数错误是由于环境问题，我把能用的lxml源码拷贝了一份。
> > 这个action失败了
> > ##_**group**_Run echo "$USERS_COVER" > ./config.json
> > �_**36;1mecho "$USERS_COVER" > ./config.json�**_0m
> > �_**36;1mpython main.py�**_0m
> > shell: /bin/bash -e _**0**_
> > env:
> > pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
> > LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
> > USERS_COVER: ***
> > ##_**endgroup**_
> > Traceback (most recent call last):
> > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 8, in 
> > import pytz
> > ModuleNotFoundError: No module named 'pytz'
> > ##_**error**_Process completed with exit code 1.

马上

**Comment by yzbwork** [comment]
> > > > requirements.txt
> > > 
> > > 
> > > 这个不需要更新，之前云函数错误是由于环境问题，我把能用的lxml源码拷贝了一份。
> > > 这个action失败了
> > > ##_**group**_Run echo "$USERS_COVER" > ./config.json
> > > �_**36;1mecho "$USERS_COVER" > ./config.json�**_0m
> > > �_**36;1mpython main.py�**_0m
> > > shell: /bin/bash -e _**0**_
> > > env:
> > > pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
> > > LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
> > > USERS_COVER: ***
> > > ##_**endgroup**_
> > > Traceback (most recent call last):
> > > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 8, in
> > > import pytz
> > > ModuleNotFoundError: No module named 'pytz'
> > > ##_**error**_Process completed with exit code 1.
> 
> 马上

thx

**Comment by srcrs** [comment]
@yzbwork 再拉取更新一下

**Comment by yzbwork** [comment]
> @yzbwork 再拉取更新一下

可以了，也部署成功了
