### ISSUE TITLE
手动同步上游代码失败，好像是被拒绝了？

### ISSUE THREAD

**Issue by 897759731** [srcrs/UnicomTask#160]
![QQ截图20210311120001](https://user-images.githubusercontent.com/36438389/110733743-71f12600-8261-11eb-8cc9-64b45f1d0b1c.jpg)

**Comment by srcrs** [comment]
@897759731 actions上游配置文件修改了，无权限，建议手动更新下

**Comment by 897759731** [comment]
> @8977759731动作是国家和

ok

**Comment by 132098089** [comment]
怎么更新？重新搞一遍吗？

**Comment by 897759731** [comment]
@132098089  对

**Comment by kaikaimj** [comment]
> @897759731 actions上游配置文件修改了，无权限，建议手动更新下
手动更新什么意思？手动同步上游代码总是报错，也按要求添加了token

**Comment by kaikaimj** [comment]
> @897759731 actions上游配置文件修改了，无权限，建议手动更新下

手动更新什么意思？手动同步上游代码总是报错，也按要求添加了token

**Comment by srcrs** [comment]
> > @897759731 actions上游配置文件修改了，无权限，建议手动更新下
> 
> 手动更新什么意思？手动同步上游代码总是报错，也按要求添加了token

把auto_merge.yml改成和我一样的，再运行就好了。

**Comment by kaikaimj** [comment]
> > > @897759731 actions上游配置文件修改了，无权限，建议手动更新下
> > 
> > 
> > 手动更新什么意思？手动同步上游代码总是报错，也按要求添加了token
> 
> 把auto_merge.yml改成和我一样的，再运行就好了。

已成功，谢谢
