### ISSUE TITLE
邮箱推送改造思路

### ISSUE THREAD

**Issue by riven-M** [srcrs/UnicomTask#168]
### 邮件推送使用个人邮箱发送
* 自主提供A邮箱 send B 邮箱 
* 可解决第三方邮箱不稳定性
* 因推送目前没有收到未知格式 建议（统计今日获得临时流量）
### 言外
* readme中关键词更换 避免和谐 
thankyou

**Comment by srcrs** [comment]
> ### 邮件推送使用个人邮箱发送
> * 自主提供A邮箱 send B 邮箱
> * 可解决第三方邮箱不稳定性
> * 因推送目前没有收到未知格式 建议（统计今日获得临时流量）
> 
> ### 言外
> * readme中关键词更换 避免和谐
>   thankyou

1.之前有考虑过，但对用户来说配置较为复杂，况且现在有很多推送渠道，邮箱只做备选。

2.获得的流量没有是临时的，到期期限暂不知，领取的流量包有到期时间。

3.谢谢提醒和建议。
