### ISSUE TITLE
没有每天自动兑换临时1g流量

### ISSUE THREAD

**Issue by a543447692a** [srcrs/UnicomTask#169]
我的没有每天自动兑换临时1g流量，多次尝试重新叉 无效

**Comment by srcrs** [comment]
> 我的没有每天自动兑换临时1g流量，多次尝试重新叉 无效

我看了你的版本应该没问题，流量包自动激活规则是，不到一天有效期才激活的

**Comment by a543447692a** [comment]
我有一个今天3.11过期包，但是手动几次运行没有兑换

**Comment by srcrs** [comment]
> 我有一个今天3.11过期包，但是手动几次运行没有兑换

我这边刚在actions测试，获取时间戳获取是对的，我明天有个包也要快到期，到时候看一下吧。

**Comment by mmkakac** [comment]
> > 我有一个今天3.11过期包，但是手动几次运行没有兑换
> 
> 我这边刚在actions测试，获取时间戳获取是对的，我明天有个包也要快到期，到时候看一下吧。

我知道为什么了，腾讯云的系统时间是比北京时间慢8小时的，所以要8点以后才会兑换今天过期的包

**Comment by kyvin8** [comment]
你好，今天测试了下，领取的1G流量日报无法自动激活，请帮忙分析下，多谢

**Comment by emengweb** [comment]
最新包自动激活当时过期流量包成功

**Comment by xxtx16648** [comment]
> > > 我有一个今天3.11过期包，但是手动几次运行没有兑换
> > 
> > 
> > 我这边刚在actions测试，获取时间戳获取是对的，我明天有个包也要快到期，到时候看一下吧。
> 
> 我知道为什么了，腾讯云的系统时间是比北京时间慢8小时的，所以要8点以后才会兑换今天过期的包

应该是git服务器的时间比北京时间慢8小时吧

**Comment by srcrs** [comment]
> > > > 我有一个今天3.11过期包，但是手动几次运行没有兑换
> > > 
> > > 
> > > 我这边刚在actions测试，获取时间戳获取是对的，我明天有个包也要快到期，到时候看一下吧。
> > 
> > 
> > 我知道为什么了，腾讯云的系统时间是比北京时间慢8小时的，所以要8点以后才会兑换今天过期的包
> 
> 应该是git服务器的时间比北京时间慢8小时吧

历史版本确实存在时区的问题，但是现在应该没有了。我这边云函数早上6：30确实是帮我激活了一个今天要激活的浏览量包。

我在Actions又测试了另外一个号:

当时时间戳：1615529020
到期时间戳：1615564799
差值：35779

正好应对了当时的时间，大约还有十个小时过期，因此流量包也就激活了。

**Comment by srcrs** [comment]
@All 我刚刚看了@emengweb的日志，也是激活成功了的。你要搞清楚不是每天自动激活流量包，而是激活要过期的流量包。
