### ISSUE TITLE
兄弟可以一起开发吗？

### ISSUE THREAD

**Issue by ovenone** [srcrs/UnicomTask#17]
另外也想学习一下你是如何准确抓到这些请求链接的。我用了几个抓包软件，在点击以后太多链接了，没找到技巧，折腾了3个小时一个也没有抓到。。。

电报id：@DFYM0

**Comment by srcrs** [comment]
> 另外也想学习一下你是如何准确抓到这些请求链接的。我用了几个抓包软件，在点击以后太多链接了，没找到技巧，折腾了3个小时一个也没有抓到。。。
> 
> 电报id：@DFYM0

欢迎一起开发，你需要学会简单的分析请求和响应的内容。

**Comment by ovenone** [comment]
目前没找到方向，抓包分析会一点，就是数据量太多了。   另外就是对这个软件的请求结构还不熟悉。    我用charles 和手机上的httpcanary   、 stream  分析起来感觉都不方便。。。    你有对请求链接上做什么筛选吗？

**Comment by ovenone** [comment]
方便加个电报好友或者wx好友吗  向你学习学习

**Comment by srcrs** [comment]
> 方便加个电报好友或者wx好友吗 向你学习学习
抱歉呐，加好友可以，但我现在没时间带新人。

**Comment by srcrs** [comment]
> 目前没找到方向，抓包分析会一点，就是数据量太多了。 另外就是对这个软件的请求结构还不熟悉。 我用charles 和手机上的httpcanary 、 stream 分析起来感觉都不方便。。。 你有对请求链接上做什么筛选吗？

没有的

**Comment by srcrs** [comment]
@ovenone 有问题再给我发邮箱吧 srcrs@foxmail.com

**Comment by ovenone** [comment]
找到方法了
