### ISSUE TITLE
积分能不能细分一下，就像mixool / HiCnUnicom那样

### ISSUE THREAD

**Issue by Ynooo** [srcrs/UnicomTask#171]
比如
总积分: 00奖励积分:00消耗奖励积分:00将过期积分: 00
昨日奖励积分:00

**Comment by srcrs** [comment]
> 比如
> 总积分: 00奖励积分:00消耗奖励积分:00将过期积分: 00
> 昨日奖励积分:00

可，实际上也就是奖励积分看着有用，其他的倒没什么

**Comment by Ynooo** [comment]
> > 比如
> > 总积分: 00奖励积分:00消耗奖励积分:00将过期积分: 00
> > 昨日奖励积分:00
> 
> 可，实际上也就是奖励积分看着有用，其他的倒没什么

我也是这样觉得，能区分定向和奖励积分也行

**Comment by srcrs** [comment]
> > > 比如
> > > 总积分: 00奖励积分:00消耗奖励积分:00将过期积分: 00
> > > 昨日奖励积分:00
> > 
> > 
> > 可，实际上也就是奖励积分看着有用，其他的倒没什么
> 
> 我也是这样觉得，能区分定向和奖励积分也行

已加上
