### ISSUE TITLE
抽奖有点问题

### ISSUE THREAD

**Issue by xxtx16648** [srcrs/UnicomTask#175]
ERROR:【天天抽奖】: 错误，原因为: 'NoneType' object has no attribute 'group'
ERROR:【积分抽奖】: 错误，原因为: 'NoneType' object has no attribute 'group'

**Comment by srcrs** [comment]
> ERROR:【天天抽奖】: 错误，原因为: 'NoneType' object has no attribute 'group'
> ERROR:【积分抽奖】: 错误，原因为: 'NoneType' object has no attribute 'group'

是的，联通公司后台在更新，更新完就好了
