### ISSUE TITLE
config.json 能不能直接从环境变量读取,不要写入文件系统?

### ISSUE THREAD

**Issue by vitock** [srcrs/UnicomTask#179]
直接写入,可能会有风险问题

**Comment by srcrs** [comment]
> 直接写入,可能会有风险问题

以前就是从环境变量读取，但是在云函数会出现一些问题，就改成了这样，写入文件会有什么风险？

**Comment by vitock** [comment]
> > 直接写入,可能会有风险问题
> 
> 以前就是从环境变量读取，但是在云函数会出现一些问题，就改成了这样，写入文件会有什么风险？

不了解 ga的虚拟机运行方式,只是单纯觉得把密钥写入文件系统不是太放心

**Comment by srcrs** [comment]
> > > 直接写入,可能会有风险问题
> > 
> > 
> > 以前就是从环境变量读取，但是在云函数会出现一些问题，就改成了这样，写入文件会有什么风险？
> 
> 不了解 ga的虚拟机运行方式,只是单纯觉得把密钥写入文件系统不是太放心

但密钥原本就是在github存储的，既然交给他了，就选择信任吧。

**Comment by vitock** [comment]
> > > > 直接写入,可能会有风险问题
> > > 
> > > 
> > > 以前就是从环境变量读取，但是在云函数会出现一些问题，就改成了这样，写入文件会有什么风险？
> > 
> > 
> > 不了解 ga的虚拟机运行方式,只是单纯觉得把密钥写入文件系统不是太放心
> 
> 但密钥原本就是在github存储的，既然交给他了，就选择信任吧。

好吧,其实不是怕ga偷数据,是怕他的虚拟机有bug,造成其他用户越界访问,不过这个也不是很重要数据,怎么方便怎么来吧,感谢你的这个项目,每日1g流量 :)
