### ISSUE TITLE
登陆出现问题

### ISSUE THREAD

**Issue by thomas502** [srcrs/UnicomTask#187]
:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!

运行后日志提示  请问怎么解决  不是初始密码  appid都对

**Comment by srcrs** [comment]
> :【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> 
> 运行后日志提示 请问怎么解决 不是初始密码 appid都对

这个问题应该是appId不对

**Comment by thomas502** [comment]
appid是对的 在别的库上就可以运行

**Comment by thomas502** [comment]
有qq或微信的联系方式吗 咱们在线聊

**Comment by srcrs** [comment]
> 有qq或微信的联系方式吗 咱们在线聊

微信号发我邮箱srcsr@foxmail.com

**Comment by thomas502** [comment]
好了   还有一个问题 多账号登陆 在日志里面看不到两个都运行的记录啊

**Comment by srcrs** [comment]
> 好了 还有一个问题 多账号登陆 在日志里面看不到两个都运行的记录啊

可以的啊，都在一个地方，你再仔细看看。
