### ISSUE TITLE
请问能否增加兑换流量包的功能

### ISSUE THREAD

**Issue by Blender-S** [srcrs/UnicomTask#19]
https://github.com/hzys/HiCnUnicom
这个可以进行多账号签到
也可以实现每天激活日流量包
使用 AutoSignMachine_lunnlew 每天领的流量想让不同的号码激活不同的流量包
说明里只能设置为某些号码激活某个流量包，不能分开设置
例如：我想设置每天为号码1激活1G流量，为号码2和3激活2G流量

**Comment by srcrs** [comment]
> https://github.com/hzys/HiCnUnicom
> 这个可以进行多账号签到
> 也可以实现每天激活日流量包
> 使用 AutoSignMachine_lunnlew 每天领的流量想让不同的号码激活不同的流量包
> 说明里只能设置为某些号码激活某个流量包，不能分开设置
> 例如：我想设置每天为号码1激活1G流量，为号码2和3激活2G流量

流量还是自己去激活比较好吧，每天能够领取的流量并不够每日激活的，程序并不能实时判断你的需求，导致激活掉的流量包浪费掉。

后面也许这样实现可能会好点：
1.每天程序运行前，检测到通用流量不多的时候，自动激活流量
2.月底，快过期的流量包给使用掉。

**Comment by Blender-S** [comment]
使用 AutoSignMachine 跑完之后每天流量大概能领 4G 左右，每天凌晨激活 1G / 2G 还是没用问题的
我的一个号码5元小天神，自带 1G 通用，用完之后每天必然会触发日租宝，每天正常使用流量不超过2G
如果能给出一个设置，每天凌晨激活自己设置好的流量包，就不用每天触发日租宝了
在之前的那个仓库里，多个账号没法独立设置，只能统一设置为所有号码激活某个流量包，暂时这样用没问题
但还是想要可以自定义针对每个号码激活不同的流量包来使用，可能要求的有点多了，不过还是要谢谢你

**Comment by srcrs** [comment]
> 使用 AutoSignMachine 跑完之后每天流量大概能领 4G 左右，每天凌晨激活 1G / 2G 还是没用问题的
> 我的一个号码5元小天神，自带 1G 通用，用完之后每天必然会触发日租宝，每天正常使用流量不超过2G
> 如果能给出一个设置，每天凌晨激活自己设置好的流量包，就不用每天触发日租宝了
> 在之前的那个仓库里，多个账号没法独立设置，只能统一设置为所有号码激活某个流量包，暂时这样用没问题
> 但还是想要可以自定义针对每个号码激活不同的流量包来使用，可能要求的有点多了，不过还是要谢谢你
AutoSignMachine确实能够领很多

**Comment by Blender-S** [comment]
可惜 AutoSignMachine 不能实现 actions 运行，不然就完美了，哈哈哈

**Comment by srcrs** [comment]
> 可惜 AutoSignMachine 不能实现 actions 运行，不然就完美了，哈哈哈

actions运行太久了，不太适合
