### ISSUE TITLE
你好怎么把程序运行时间提前到晚上十二点

### ISSUE THREAD

**Issue by xiao9469** [srcrs/UnicomTask#204]
作者你好，这个程序是每天早上七点三十分运行的，请问怎么修改成晚上过了十二点就运行呢？

**Comment by lxl6125** [comment]
编辑.github/workflows/UnicomTask.yml
把cron: '30 22 * * *'改成cron: '0 16 * * *'

**Comment by Zoenzao** [comment]
晚上12点 很多时候联通维护系统 有可能失败哦

**Comment by lxl6125** [comment]
> 晚上12点 很多时候联通维护系统 有可能失败哦

确实，联通经常半夜维护系统

**Comment by xiao9469** [comment]
> 编辑.github/workflows/UnicomTask.yml
> 把cron: '30 22 * * *'改成cron: '0 16 * * *'

谢谢，懂了
