### ISSUE TITLE
action报错了

### ISSUE THREAD

**Issue by csteike** [srcrs/UnicomTask#21]
Run python main.py

[2021-02-21 10:48:41,209]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in <module>
    if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
TypeError: object of type 'NoneType' has no len()
Error: Process completed with exit code 1.

**Comment by srcrs** [comment]
> 
> Run python main.py
> 
> [2021-02-21 10:48:41,209]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> Traceback (most recent call last):
>   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in <module>
>     if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> TypeError: object of type 'NoneType' has no len()
> Error: Process completed with exit code 1.

没有填写appid

**Comment by csteike** [comment]
> 
> 
> > Run python main.py
> > [2021-02-21 10:48:41,209]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> > Traceback (most recent call last):
> > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in 
> > if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> > TypeError: object of type 'NoneType' has no len()
> > Error: Process completed with exit code 1.
> 
> 没有填写appid

谢谢，解决了，我重新填了一下

**Comment by csteike** [comment]
> 
> 
> > Run python main.py
> > [2021-02-21 10:48:41,209]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> > Traceback (most recent call last):
> > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in 
> > if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> > TypeError: object of type 'NoneType' has no len()
> > Error: Process completed with exit code 1.
> 
> 没有填写appid

但是又报错了

[2021-02-21 11:00:32,208]:INFO:【每日签到】: 打卡成功,翻倍成功
[2021-02-21 11:00:45,327]:INFO:【天天抽奖】: 谢谢参与~ x1
[2021-02-21 11:00:58,759]:INFO:【天天抽奖】: 谢谢参与~ x2
[2021-02-21 11:01:12,198]:INFO:【天天抽奖】: 2MB x3
[2021-02-21 11:01:27,029]:INFO:【积分抽奖】: 谢谢参与~ x免费
[2021-02-21 11:01:27,477]:INFO:【游戏中心签到】: 获得1积分
[2021-02-21 11:01:41,901]:INFO:【游戏频道打卡】: 获得1积分
[2021-02-21 11:01:56,938]:INFO:【100定向积分】: 领取成功
[2021-02-21 11:02:11,433]:INFO:【东奥积分活动】: 领取成功，600积分
[2021-02-21 11:02:29,140]:INFO:【沃之树-领流量】: 4M流量 x1
[2021-02-21 11:02:41,569]:INFO:【沃之树-领流量】: 4M流量 x2
[2021-02-21 11:02:58,987]:INFO:【沃之树-领流量】: 4M流量 x3
[2021-02-21 11:03:11,492]:INFO:【沃之树-浇水】: 获得3培养值
[2021-02-21 11:03:42,610]:INFO:【100M寻宝箱】: 获得100M流量
[2021-02-21 11:03:57,832]:INFO:【4G流量包-看视频】: 获得30M流量 x1
[2021-02-21 11:04:18,278]:INFO:【4G流量包-下软件】: 获得50M流量 x1
[2021-02-21 11:04:34,646]:INFO:【4G流量包-看视频】: 获得30M流量 x2
[2021-02-21 11:04:48,067]:INFO:【4G流量包-下软件】: 获得50M流量 x2
[2021-02-21 11:05:08,495]:INFO:【4G流量包-看视频】: 获得30M流量 x3
[2021-02-21 11:05:26,890]:INFO:【4G流量包-下软件】: 获得50M流量 x3
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in <module>
    if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
TypeError: object of type 'NoneType' has no len()
Error: Process completed with exit code 1.

**Comment by srcrs** [comment]
> > 
> > 
> > > Run python main.py
> > > [2021-02-21 10:48:41,209]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> > > Traceback (most recent call last):
> > > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in 
> > > if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> > > TypeError: object of type 'NoneType' has no len()
> > > Error: Process completed with exit code 1.
> > 
> > 没有填写appid
> 
> 但是又报错了
> 
> [2021-02-21 11:00:32,208]:INFO:【每日签到】: 打卡成功,翻倍成功
> [2021-02-21 11:00:45,327]:INFO:【天天抽奖】: 谢谢参与~ x1
> [2021-02-21 11:00:58,759]:INFO:【天天抽奖】: 谢谢参与~ x2
> [2021-02-21 11:01:12,198]:INFO:【天天抽奖】: 2MB x3
> [2021-02-21 11:01:27,029]:INFO:【积分抽奖】: 谢谢参与~ x免费
> [2021-02-21 11:01:27,477]:INFO:【游戏中心签到】: 获得1积分
> [2021-02-21 11:01:41,901]:INFO:【游戏频道打卡】: 获得1积分
> [2021-02-21 11:01:56,938]:INFO:【100定向积分】: 领取成功
> [2021-02-21 11:02:11,433]:INFO:【东奥积分活动】: 领取成功，600积分
> [2021-02-21 11:02:29,140]:INFO:【沃之树-领流量】: 4M流量 x1
> [2021-02-21 11:02:41,569]:INFO:【沃之树-领流量】: 4M流量 x2
> [2021-02-21 11:02:58,987]:INFO:【沃之树-领流量】: 4M流量 x3
> [2021-02-21 11:03:11,492]:INFO:【沃之树-浇水】: 获得3培养值
> [2021-02-21 11:03:42,610]:INFO:【100M寻宝箱】: 获得100M流量
> [2021-02-21 11:03:57,832]:INFO:【4G流量包-看视频】: 获得30M流量 x1
> [2021-02-21 11:04:18,278]:INFO:【4G流量包-下软件】: 获得50M流量 x1
> [2021-02-21 11:04:34,646]:INFO:【4G流量包-看视频】: 获得30M流量 x2
> [2021-02-21 11:04:48,067]:INFO:【4G流量包-下软件】: 获得50M流量 x2
> [2021-02-21 11:05:08,495]:INFO:【4G流量包-看视频】: 获得30M流量 x3
> [2021-02-21 11:05:26,890]:INFO:【4G流量包-下软件】: 获得50M流量 x3
> Traceback (most recent call last):
>   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in <module>
>     if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> TypeError: object of type 'NoneType' has no len()
> Error: Process completed with exit code 1.

这个是我的锅，你在actions手动运行一下auto_merge，修复一下这个错误。

**Comment by csteike** [comment]
> 
> 
> > > > Run python main.py
> > > > [2021-02-21 10:48:41,209]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> > > > Traceback (most recent call last):
> > > > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in
> > > > if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> > > > TypeError: object of type 'NoneType' has no len()
> > > > Error: Process completed with exit code 1.
> > > 
> > > 
> > > 没有填写appid
> > 
> > 
> > 但是又报错了
> > [2021-02-21 11:00:32,208]:INFO:【每日签到】: 打卡成功,翻倍成功
> > [2021-02-21 11:00:45,327]:INFO:【天天抽奖】: 谢谢参与~ x1
> > [2021-02-21 11:00:58,759]:INFO:【天天抽奖】: 谢谢参与~ x2
> > [2021-02-21 11:01:12,198]:INFO:【天天抽奖】: 2MB x3
> > [2021-02-21 11:01:27,029]:INFO:【积分抽奖】: 谢谢参与~ x免费
> > [2021-02-21 11:01:27,477]:INFO:【游戏中心签到】: 获得1积分
> > [2021-02-21 11:01:41,901]:INFO:【游戏频道打卡】: 获得1积分
> > [2021-02-21 11:01:56,938]:INFO:【100定向积分】: 领取成功
> > [2021-02-21 11:02:11,433]:INFO:【东奥积分活动】: 领取成功，600积分
> > [2021-02-21 11:02:29,140]:INFO:【沃之树-领流量】: 4M流量 x1
> > [2021-02-21 11:02:41,569]:INFO:【沃之树-领流量】: 4M流量 x2
> > [2021-02-21 11:02:58,987]:INFO:【沃之树-领流量】: 4M流量 x3
> > [2021-02-21 11:03:11,492]:INFO:【沃之树-浇水】: 获得3培养值
> > [2021-02-21 11:03:42,610]:INFO:【100M寻宝箱】: 获得100M流量
> > [2021-02-21 11:03:57,832]:INFO:【4G流量包-看视频】: 获得30M流量 x1
> > [2021-02-21 11:04:18,278]:INFO:【4G流量包-下软件】: 获得50M流量 x1
> > [2021-02-21 11:04:34,646]:INFO:【4G流量包-看视频】: 获得30M流量 x2
> > [2021-02-21 11:04:48,067]:INFO:【4G流量包-下软件】: 获得50M流量 x2
> > [2021-02-21 11:05:08,495]:INFO:【4G流量包-看视频】: 获得30M流量 x3
> > [2021-02-21 11:05:26,890]:INFO:【4G流量包-下软件】: 获得50M流量 x3
> > Traceback (most recent call last):
> > File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 309, in 
> > if len(os.environ.get('DINGTALK_WEBHOOK')) !=0:
> > TypeError: object of type 'NoneType' has no len()
> > Error: Process completed with exit code 1.
> 
> 这个是我的锅，你在actions手动运行一下auto_merge，修复一下这个错误。

你这个auto merge也报错了....


Run git push origin $DOWNSTREAM_BRANCH
To https://github.com/csteike/UnicomTask
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/UnicomTask.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/csteike/UnicomTask'
Error: Process completed with exit code 1.

**Comment by srcrs** [comment]
@csteike .github/workflows/UnicomTask.yml文件

37行下面添加下面这个代码

```yml
DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
```
弄成和我一样的

**Comment by z2135** [comment]
> @csteike.gizub/工作流/UnicomTask.yml文件
> 
> 37行下面添加下面这个代码
> 
> ```yaml
> DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
> ```
> 
> 弄成和我一样的

我也是这个问题，这样操作了依旧报错

**Comment by srcrs** [comment]
> > @csteike.gizub/工作流/UnicomTask.yml文件
> > 37行下面添加下面这个代码
> > ```yaml
> > DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
> > ```
> > 
> > 
> > 弄成和我一样的
> 
> 我也是这个问题，这样操作了依旧报错

因为你是多账号，底下的也都要加上
