### ISSUE TITLE
游戏中心签到积分领取、寻宝箱任务一直失败

### ISSUE THREAD

**Issue by Serifff** [srcrs/UnicomTask#223]
推送记录：
UnicomTask每日报表=【登录】: 6771
【积分余额】: 585
【每日签到】: 打卡成功,翻倍失败
【1G流量日包】: 领取成功
【天天抽奖】: 谢谢参与~ x1
【天天抽奖】: 谢谢参与~ x2
【天天抽奖】: 2MB x3
【积分抽奖】: 谢谢参与~ x免费
【100定向积分】: 领取成功
【东奥积分活动】: 领取成功，300积分
【游戏中心签到】: 打卡成功，奖励发放失败
【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过
【100M寻宝箱】: 任务失败
【4G流量包-看视频】: 获得30M流量 x1
【4G流量包-下软件】: 获得50M流量 x1
【4G流量包-看视频】: 获得30M流量 x2
【4G流量包-下软件】: 获得50M流量 x2
【4G流量包-看视频】: 获得30M流量 x3
【4G流量包-下软件】: 获得50M流量 x3
【沃之树-领流量】: 4M流量 x1
【沃之树-领流量】: 4M流量 x2
【沃之树-领流量】: 4M流量 x3
【沃之树-浇水】: 获得3培养值
【即将过期流量包】: 暂无
1、
![_20210313_140123.JPG](https://user-images.githubusercontent.com/80401151/111021026-a3eebd80-8404-11eb-92ef-2ca51d5d3edc.JPG)显示已打卡，但积分获取记录里没有打卡获取的积分记录，也就是说无法正常领取游戏中心签到积分。
2、
![Screenshot_20210313-140407.png](https://user-images.githubusercontent.com/80401151/111021090-ffb94680-8404-11eb-8080-1bb6d597c227.png)
宝箱任务的积分同样无法正常获取。
请问大佬如果这是BUG暂时无法解决，可以更改我个人的代码取消这两个任务的自动执行，由我手动完成任务吗？

**Comment by srcrs** [comment]
> 推送记录：
> UnicomTask每日报表=【登录】: 6771
> 【积分余额】: 585
> 【每日签到】: 打卡成功,翻倍失败
> 【1G流量日包】: 领取成功
> 【天天抽奖】: 谢谢参与~ x1
> 【天天抽奖】: 谢谢参与~ x2
> 【天天抽奖】: 2MB x3
> 【积分抽奖】: 谢谢参与~ x免费
> 【100定向积分】: 领取成功
> 【东奥积分活动】: 领取成功，300积分
> 【游戏中心签到】: 打卡成功，奖励发放失败
> 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过
> 【100M寻宝箱】: 任务失败
> 【4G流量包-看视频】: 获得30M流量 x1
> 【4G流量包-下软件】: 获得50M流量 x1
> 【4G流量包-看视频】: 获得30M流量 x2
> 【4G流量包-下软件】: 获得50M流量 x2
> 【4G流量包-看视频】: 获得30M流量 x3
> 【4G流量包-下软件】: 获得50M流量 x3
> 【沃之树-领流量】: 4M流量 x1
> 【沃之树-领流量】: 4M流量 x2
> 【沃之树-领流量】: 4M流量 x3
> 【沃之树-浇水】: 获得3培养值
> 【即将过期流量包】: 暂无
> 1、
> ![_20210313_140123.JPG](https://user-images.githubusercontent.com/80401151/111021026-a3eebd80-8404-11eb-92ef-2ca51d5d3edc.JPG)显示已打卡，但积分获取记录里没有打卡获取的积分记录，也就是说无法正常领取游戏中心签到积分。
> 2、
> ![Screenshot_20210313-140407.png](https://user-images.githubusercontent.com/80401151/111021090-ffb94680-8404-11eb-8080-1bb6d597c227.png)
> 宝箱任务的积分同样无法正常获取。
> 请问大佬如果这是BUG暂时无法解决，可以更改我个人的代码取消这两个任务的自动执行，由我手动完成任务吗？

更新到最新代码，如果检测到会触发防刷，将不会帮你执行，你试下可以不。

**Comment by Serifff** [comment]
> 
> 
> > 推送记录：
> > UnicomTask每日报表=【登录】: 6771
> > 【积分余额】: 585
> > 【每日签到】: 打卡成功,翻倍失败
> > 【1G流量日包】: 领取成功
> > 【天天抽奖】: 谢谢参与~ x1
> > 【天天抽奖】: 谢谢参与~ x2
> > 【天天抽奖】: 2MB x3
> > 【积分抽奖】: 谢谢参与~ x免费
> > 【100定向积分】: 领取成功
> > 【东奥积分活动】: 领取成功，300积分
> > 【游戏中心签到】: 打卡成功，奖励发放失败
> > 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过
> > 【100M寻宝箱】: 任务失败
> > 【4G流量包-看视频】: 获得30M流量 x1
> > 【4G流量包-下软件】: 获得50M流量 x1
> > 【4G流量包-看视频】: 获得30M流量 x2
> > 【4G流量包-下软件】: 获得50M流量 x2
> > 【4G流量包-看视频】: 获得30M流量 x3
> > 【4G流量包-下软件】: 获得50M流量 x3
> > 【沃之树-领流量】: 4M流量 x1
> > 【沃之树-领流量】: 4M流量 x2
> > 【沃之树-领流量】: 4M流量 x3
> > 【沃之树-浇水】: 获得3培养值
> > 【即将过期流量包】: 暂无
> > 1、
> > ![_20210313_140123.JPG](https://user-images.githubusercontent.com/80401151/111021026-a3eebd80-8404-11eb-92ef-2ca51d5d3edc.JPG)显示已打卡，但积分获取记录里没有打卡获取的积分记录，也就是说无法正常领取游戏中心签到积分。
> > 2、
> > ![Screenshot_20210313-140407.png](https://user-images.githubusercontent.com/80401151/111021090-ffb94680-8404-11eb-8080-1bb6d597c227.png)
> > 宝箱任务的积分同样无法正常获取。
> > 请问大佬如果这是BUG暂时无法解决，可以更改我个人的代码取消这两个任务的自动执行，由我手动完成任务吗？
> 
> 更新到最新代码，如果检测到会触发防刷，将不会帮你执行，你试下可以不。

嗯嗯谢谢大佬，已更新代码，明早看看什么情况

**Comment by Serifff** [comment]
今天早晨的推送信息：

UnicomTask每日报表=【登录】: 6771
【通信积分】: 0
【奖励积分】: 404
【定向积分】: 800
【每日签到】: 打卡成功,翻倍成功
【1G流量日包】: 领取成功
【天天抽奖】: 谢谢参与~ x1
【天天抽奖】: 谢谢参与~ x2
【天天抽奖】: 2MB x3
【积分抽奖】: 5MB流量 x免费
【100定向积分】: 领取成功
【东奥积分活动】: 领取成功，300积分
【娱乐中心任务】: 触发防刷，跳过
【4G流量包-看视频】: 获得30M流量 x1
【4G流量包-下软件】: 获得50M流量 x1
【4G流量包-看视频】: 获得30M流量 x2
【4G流量包-下软件】: 获得50M流量 x2
【4G流量包-看视频】: 获得30M流量 x3
【4G流量包-下软件】: 获得50M流量 x3
【沃之树-领流量】: 4M流量 x1
【沃之树-领流量】: 4M流量 x2
【沃之树-领流量】: 4M流量 x3
【沃之树-浇水】: 获得3培养值
【即将过期流量包】: 激活成功

侦测到触发防刷，成功跳过游戏中心打卡以及宝箱任务。目前没什么bug了，谢谢大佬😊
