### ISSUE TITLE
是否考虑增加游戏中心玩游戏领流量？

### ISSUE THREAD

**Issue by zhaokai5520** [srcrs/UnicomTask#227]
每个游戏是100M
![Screenshot_20210313_232351_com sinovatech unicom](https://user-images.githubusercontent.com/22487623/111035071-91e83b80-8453-11eb-936a-403d54ecf5cb.png)

**Comment by heibaigame** [comment]
兄弟，你这个推送咋搞的

**Comment by zhaokai5520** [comment]
> 你这个推送咋搞的
什么推送？联通手机营业厅首页就有入口啊

**Comment by xxtx16648** [comment]
我直接连入口都不显示了，游戏板块已凉。

**Comment by shanmoweiyunjun** [comment]
还能领

**Comment by srcrs** [comment]
不可以做。
