### ISSUE TITLE
钉钉推送签名不匹配

### ISSUE THREAD

**Issue by mima454188** [srcrs/UnicomTask#236]
![微信图片_20210314104753](https://user-images.githubusercontent.com/74166821/111055651-3188e680-84b3-11eb-9272-58bdd85a2246.png)
![2313](https://user-images.githubusercontent.com/74166821/111055661-58471d00-84b3-11eb-9907-19975e974110.png)
按上面配置，最后提示签名不匹配。请大佬指点，谢谢了！

**Comment by srcrs** [comment]
> ![微信图片_20210314104753](https://user-images.githubusercontent.com/74166821/111055651-3188e680-84b3-11eb-9272-58bdd85a2246.png)
> ![2313](https://user-images.githubusercontent.com/74166821/111055661-58471d00-84b3-11eb-9907-19975e974110.png)
> 按上面配置，最后提示签名不匹配。请大佬指点，谢谢了！

设置机器人关键词为`UnicomTask`

**Comment by mima454188** [comment]
> > ![微信图片_20210314104753](https://user-images.githubusercontent.com/74166821/111055651-3188e680-84b3-11eb-9272-58bdd85a2246.png)
> > ![2313](https://user-images.githubusercontent.com/74166821/111055661-58471d00-84b3-11eb-9907-19975e974110.png)
> > 按上面配置，最后提示签名不匹配。请大佬指点，谢谢了！
> 
> 设置机器人关键词为`UnicomTask`

谢谢大佬，我知道问题在哪了，我用原来的机器人的token。但是我原来的机器人加签了，导致改了关键字还是签名失败。
我重现创建了一个机器人的并设置好关键字UnicomTask，现在推送成功了。
![image](https://user-images.githubusercontent.com/74166821/111069420-f795ff80-8507-11eb-9888-4799d6ed06d4.png)

**Comment by srcrs** [comment]
> > > ![微信图片_20210314104753](https://user-images.githubusercontent.com/74166821/111055651-3188e680-84b3-11eb-9272-58bdd85a2246.png)
> > > ![2313](https://user-images.githubusercontent.com/74166821/111055661-58471d00-84b3-11eb-9907-19975e974110.png)
> > > 按上面配置，最后提示签名不匹配。请大佬指点，谢谢了！
> > 
> > 
> > 设置机器人关键词为`UnicomTask`
> 
> 谢谢大佬，我知道问题在哪了，我用原来的机器人的token。但是我原来的机器人加签了，导致改了关键字还是签名失败。
> 我重现创建了一个机器人的并设置好关键字UnicomTask，现在推送成功了。
> ![image](https://user-images.githubusercontent.com/74166821/111069420-f795ff80-8507-11eb-9888-4799d6ed06d4.png)

好的👌
