### ISSUE TITLE
不太建议使用AC执行任务

### ISSUE THREAD

**Issue by YamTian** [srcrs/UnicomTask#243]
只是提醒一下
滥用github actions资源
**可能会封库**

**Comment by srcrs** [comment]
> 只是提醒一下
> 滥用github actions资源
> **可能会封库**

这个问题应该不大，一天运行一次，每次只运行大约90秒，此外，也提供了云函数的使用方式。

**Comment by YamTian** [comment]
但不管怎么说
谢谢你的辛勤付出
