### ISSUE TITLE
群主可以不可以建一个微信群

### ISSUE THREAD

**Issue by Zhuliyer** [srcrs/UnicomTask#244]
作者大大，创建一个微信群方便大家伙交流，也能让大家知道您发布新版本的时候我们第一时间也能了解 ，怎么样作者大大

**Comment by srcrs** [comment]
> 作者大大，创建一个微信群方便大家伙交流，也能让大家知道您发布新版本的时候我们第一时间也能了解 ，怎么样作者大大

最近在找工作的，可能会没时间回复你们消息。那就一会儿建一个吧，方便大家交流，互帮互助。

**Comment by srcrs** [comment]
> 作者大大，创建一个微信群方便大家伙交流，也能让大家知道您发布新版本的时候我们第一时间也能了解 ，怎么样作者大大

已建好了

**Comment by madaxiaya** [comment]
能拉一下吗
