### ISSUE TITLE
有移动的吗

### ISSUE THREAD

**Issue by xaoyaoo** [srcrs/UnicomTask#254]
我用的移动卡

**Comment by if1y** [comment]
这边建议办一张联通卡呢

**Comment by srcrs** [comment]
> 这边建议办一张联通卡呢

支持

**Comment by srcrs** [comment]
> 我用的移动卡

我并不定制脚本

**Comment by axh2018** [comment]
转网，哈哈哈

**Comment by liyue11112** [comment]
哈哈，在办一个卡


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "srcrs/UnicomTask"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上11:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [srcrs/UnicomTask] 有移动的吗 (#254)





 
转网，哈哈哈

**Comment by xaoyaoo** [comment]
> > 我用的移动卡
> 
> 我并不定制脚本

有没有其他作者开发的移动的。
