### ISSUE TITLE
好像没有成功哈

### ISSUE THREAD

**Issue by a1274989872** [srcrs/UnicomTask#26]
感觉没有签到成功

**Comment by srcrs** [comment]
> 感觉没有签到成功

？为什么呢

**Comment by a1274989872** [comment]
刚刚用这个东西，怎么看他的运行状态呢？找不到状态栏

**Comment by a1274989872** [comment]
![1流量](https://user-images.githubusercontent.com/79441269/108689023-8d56f400-7533-11eb-97ae-e64af4b2bc8b.png)
这个状态在那个地方查看呢？

**Comment by a1274989872** [comment]
这个是截图别人的，不知道在那个地方

**Comment by a1274989872** [comment]
> > 感觉没有签到成功
> 
> ？为什么呢

在吗

**Comment by srcrs** [comment]
> > > 感觉没有签到成功
> > 
> > ？为什么呢
> 
> 在吗

Actions 里

**Comment by a1274989872** [comment]
> > > > 感觉没有签到成功
> > > 
> > > 
> > > ？为什么呢
> > 
> > 
> > 在吗
> 
> 动作里

请问功能里面有：看视频沃之树浇水吗？

**Comment by a1274989872** [comment]
反馈：浇水功能好像没效果！

**Comment by a1274989872** [comment]
> > > > 感觉没有签到成功
> > > 
> > > 
> > > ？为什么呢
> > 
> > 
> > 在吗
> 
> 动作里

反馈：浇水功能好像没效果！

**Comment by a1274989872** [comment]
> > > > 感觉没有签到成功
> > > 
> > > 
> > > ？为什么呢
> > 
> > 
> > 在吗
> 
> Actions 里

有联系方式吗？我反馈一下问题

**Comment by srcrs** [comment]
> > > > > 感觉没有签到成功
> > > > 
> > > > 
> > > > ？为什么呢
> > > 
> > > 
> > > 在吗
> > 
> > Actions 里
> 
> 有联系方式吗？我反馈一下问题

srcrs@foxmail.com
