### ISSUE TITLE
能否支持自动激活每日领取的1G流量日包

### ISSUE THREAD

**Issue by blizzards0ne** [srcrs/UnicomTask#266]
每日领取1G日包后，需要3日内手工激活，否则过期浪费。
若能自动激活，则每日流量都基本不操心了。

**Comment by TianchengOrange** [comment]
***2021-03-16 07:00:39,681***:INFO:【沃之树-浇水】: 获得3培养值
***2021-03-16 07:00:43,228***:INFO:【即将过期流量包】: 激活成功

**Comment by blizzards0ne** [comment]
> _**2021-03-16 07:00:39,681**_:INFO:【沃之树-浇水】: 获得3培养值
> _**2021-03-16 07:00:43,228**_:INFO:【即将过期流量包】: 激活成功

我才刚开始用这个脚本2天，意思是到第3天过期的时候，会自动激活这个1G日包？

**Comment by if1y** [comment]
脚本运行时小于24小时有效期，表示即将过期
