### ISSUE TITLE
TGbot消息推送重复两条

### ISSUE THREAD

**Issue by smilonely** [srcrs/UnicomTask#315]
我填了两个账号，里面分别填了TGbot信息。每次运行每个账号分别推送了两次。

**Comment by smilonely** [comment]
TGbot都是同样的信息，同样的Token同样的ID。

**Comment by srcrs** [comment]
> 我填了两个账号，里面分别填了TGbot信息。每次运行每个账号分别推送了两次。

不会吧，检查下两次推送的账号是否一样，我这边看代码和日志应该是没问题的

**Comment by smilonely** [comment]
可能是我手动运行的问题，明天再看看

**Comment by smilonely** [comment]
> 
> 
> > 我填了两个账号，里面分别填了TGbot信息。每次运行每个账号分别推送了两次。
> 
> 不会吧，检查下两次推送的账号是否一样，我这边看代码和日志应该是没问题的

我看了今天早上的推送，是正常的，可能是跟我手动运行的操作有关
