### ISSUE TITLE
auto_merg报错

### ISSUE THREAD

**Issue by fys666** [srcrs/UnicomTask#32]
`Run git push origin $DOWNSTREAM_BRANCH
  git push origin $DOWNSTREAM_BRANCH
  shell: /bin/bash -e {0}
  env:
    DOWNSTREAM_BRANCH: main
    TZ: Asia/Shanghai
To https://github.com/fys666/UnicomTask
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/UnicomTask.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/fys666/UnicomTask'
Error: Process completed with exit code 1.
`

**Comment by fys666** [comment]
Run git push origin $DOWNSTREAM_BRANCH
  git push origin $DOWNSTREAM_BRANCH
  shell: /bin/bash -e {0}
  env:
    DOWNSTREAM_BRANCH: main
    TZ: Asia/Shanghai
To https://github.com/fys666/UnicomTask
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/UnicomTask.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/fys666/UnicomTask'
Error: Process completed with exit code 1.

**Comment by srcrs** [comment]
当上游仓库Actions配置文件发生变动，就会出现更新失败的情况，刚才试了下pull也同样会出现这样的情况，有能力还是建议手动去更新吧。

**Comment by fys666** [comment]
好的，谢谢，每周我也登陆一下github看看，辛苦了！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "srcrs"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 下午4:27
收件人: "srcrs/UnicomTask"<UnicomTask@noreply.github.com&gt;; 
抄送: "王铁柱"<1432618546@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [srcrs/UnicomTask] auto_merg报错 (#32)





 
当上游仓库Actions配置文件发生变动，就会出现更新失败的情况，刚才试了下pull也同样会出现这样的情况，有能力还是建议手动去更新吧。
