### ISSUE TITLE
云函数有3处问题，不知道有什么影响

### ISSUE THREAD

**Issue by SymonChu** [srcrs/UnicomTask#321]
Anomalous backslash in string: '\w'. String constant might be missing an r prefix.
Unused variable 'data2'
Unused variable 'param'

**Comment by srcrs** [comment]
能正常运行吗？这个是由于代码不规范导致，存在未使用的变量，还有个字符串存在什么问题

**Comment by SymonChu** [comment]
刚不能正常运行，后又重新部署了一下可以正常运行了。

**Comment by srcrs** [comment]
好吧，我有时间把多余的代码去掉吧。
