### ISSUE TITLE
自动激活流量问题

### ISSUE THREAD

**Issue by 546220777** [srcrs/UnicomTask#327]
大佬  请问下  可以设置成领取1g流量后自动激活呀  。给父母跑的号  他们又不会激活

**Comment by srcrs** [comment]
从第三天起，就会自动帮你激活第一天领取的流量，不浪费为原则。

**Comment by 546220777** [comment]
> 从第三天起，就会自动帮你激活第一天领取的流量，不浪费为原则。

好的 感谢大佬这么好的项目
