### ISSUE TITLE
刷流量和积分被修复了，刷不了

### ISSUE THREAD

**Issue by 3473561517** [srcrs/UnicomTask#329]

**Comment by Silentely** [comment]
用的人多了，到处去宣传，黄是迟早的

**Comment by 3473561517** [comment]
应该可以救活吧，毕竟活动还在

**Comment by AgentWRY** [comment]
> 应该可以救活吧，毕竟活动还在
流量应该可以 积分是凉了

**Comment by Silentely** [comment]
> 应该可以救活吧，毕竟活动还在
> 流量应该可以 积分是凉了

流量凉了 玩游戏那个 地址由网页改成小程序了

**Comment by AgentWRY** [comment]
不清楚哎 已经刷的够多了 不亏就完事啦

Adair ***@***.***> 于2021年3月21日周日 下午1:32写道：

**Comment by srcrs** [comment]
> 

非本项目相关，建议到别处讨论。

**Comment by AgentWRY** [comment]
好的好的 抱歉抱歉

srcrs ***@***.***> 于2021年3月21日周日 下午1:42写道：
