### ISSUE TITLE
项目正常运行24s失败了，是为啥

### ISSUE THREAD

**Issue by theJinFei** [srcrs/UnicomTask#330]
显示 process completed with exit code 1

**Comment by 3473561517** [comment]
联通修复了，等作者更新文件

**Comment by srcrs** [comment]
> 显示 process completed with exit code 1

你的账号信息填写错了，注意看下日志。

**Comment by 3473561517** [comment]
应该没错啊，运行后多了几积分，但是流量不行了，很多人都这样

**Comment by srcrs** [comment]
> 应该没错啊，运行后多了几积分，但是流量不行了，很多人都这样

但是你说的是别的项目吧，本项目只能领取少量流量

**Comment by 3473561517** [comment]
确实是别的项目，我也是昨晚刚用这个项目的

**Comment by Sumouruge2390** [comment]
> 确实是别的项目，我也是昨晚刚用这个项目的

你说的是游戏中心3G流量吧，我也失效了
