### ISSUE TITLE
大佬 微信通知运行失败啊 

### ISSUE THREAD

**Issue by LoveForeverBoa** [srcrs/UnicomTask#334]
![QQ截图20210321215755](https://user-images.githubusercontent.com/68955955/111907508-9e424900-8a90-11eb-90e5-99544e114dc4.png)

我是这样写的  哪里有问题没啊
[
    {
        "username": "13",
        "password": "3",
        "appId": "1f0"
    },
    {
        "username": "15",
        "password": "30",
        "appId": "1f7af757c",
        "email": "28com",
        "enterpriseWechat": {
	 "id": "",
          "agentld": "",
           "secret": "jR8"
        }
    }
]

**Comment by srcrs** [comment]
格式没有问题，注意下id和secret是否填错了。

**Comment by LoveForeverBoa** [comment]
> 
> 格式没有问题，注意下id和secret是否填错了。

谢谢哈 多了一个空格
