### ISSUE TITLE
部署到云函数上，main.py notify.py中的log日志路径存在写权限问题 

### ISSUE THREAD

**Issue by heooos** [srcrs/UnicomTask#342]
直接使用./会报路径无权限。 我自己将./ 改为  /tmp路径，但是不清楚有什么影响

**Comment by srcrs** [comment]
你是自己手动部署的吗？的确是这样，云函数只有/tmp目录下能存取文件，如果使用actions部署，或者我写的本地部署脚本，会直接把目录路径修改成/tmp的。

**Comment by heooos** [comment]
> 你是自己手动部署的吗？的确是这样，云函数只有/tmp目录下能存取文件，如果使用actions部署，或者我写的本地部署脚本，会直接把目录路径修改成/tmp的。

是的，手动部署的。 追错误日志自己手动改了
