### ISSUE TITLE
可以考虑下tg推送吗

### ISSUE THREAD

**Issue by FuxkTME** [srcrs/UnicomTask#37]

**Comment by srcrs** [comment]
@FuxkTME 抱歉 tg我不太熟悉

**Comment by FuxkTME** [comment]
![Uploading Screenshot_2021-02-24-18-22-33-506_org.telegram.messenger.jpg…]()
大佬我改了一下，要不你完善一下

**Comment by FuxkTME** [comment]
> @FuxkTME 抱歉 tg我不太熟悉

我fork的仓库里修改了一下，可以使用tg推送了，你可以看看

**Comment by FuxkTME** [comment]
就是推送格式我还没弄好

**Comment by srcrs** [comment]
> 就是推送格式我还没弄好

消息格式给我看一下吧。

**Comment by FuxkTME** [comment]
> > 就是推送格式我还没弄好
> 
> 消息格式给我看一下吧。

{'【登录】: 3482\n【每日签到】: 您今天已经签到啦\n【天天抽奖】: 用户机会次数不足 x1\n【天天抽奖】: 用户机会次数不足 x2\n【天天抽奖】: 用户机会次数不足 x3\n【积分抽奖】: 用户机会次数不足 x免费\n【积分抽奖】: 用户机会次数不足 x1\n【积分抽奖】: 用户机会次数不足 x2\n【积分抽奖】: 用户机会次数不足 x3\n【积分抽奖】: 用户机会次数不足 x4\n【积分抽奖】: 用户机会次数不足 x5\n【积分抽奖】: 用户机会次数不足 x6\n【积分抽奖】: 用户机会次数不足 x7\n【积分抽奖】: 用户机会次数不足 x8\n【积分抽奖】: 用户机会次数不足 x9\n【积分抽奖】: 用户机会次数不足 x10\n【积分抽奖】: 用户机会次数不足 x11\n【积分抽奖】: 用户机会次数不足 x12\n【积分抽奖】: 用户机会次数不足 x13\n【积分抽奖】: 用户机会次数不足 x14\n【积分抽奖】: 用户机会次数不足 x15\n【100定向积分】: 不可重复领取\n【东奥积分活动】: 领取失败，已领取请次日在领取\n【沃之树-浇水】: 获得0培养值\n【游戏中心签到】: 打卡重复\n【游戏频道打卡】: 游戏积分领取失败,今日已领取过改积分\n【100M寻宝箱】: 任务失败\n【4G流量包-看视频】: 已完成 x1\n【4G流量包-下软件】: 已完成 x1\n【4G流量包-看视频】: 已完成 x2\n【4G流量包-下软件】: 已完成 x2\n【4G流量包-看视频】: 已完成 x3\n【4G流量包-下软件】: 已完成 x3\n', 'UnicomTask每日报表'}

**Comment by srcrs** [comment]
@FuxkTME 现在修好了吗？

**Comment by FuxkTME** [comment]
> @FuxkTME 现在修好了吗？
![image](https://user-images.githubusercontent.com/45877136/109005657-29742d00-76e5-11eb-8559-441a84cf2536.png)

**Comment by FuxkTME** [comment]
> @FuxkTME 现在修好了吗？

只能做到这样了

**Comment by srcrs** [comment]
> > @FuxkTME 现在修好了吗？
> 
> 只能做到这样了

可以，很不错了，把pr提交过来吧
