### ISSUE TITLE
【登录】: 为了您的信息安全，请改用短信验证码登录或者在服务密码框里输入开户证件后6位进行登录，带来不便敬请谅解(注：身份证最后一位为X的用数字0代替)。

### ISSUE THREAD

**Issue by lszh0147** [srcrs/UnicomTask#373]
修改为：开户证件后6位进行登录 提示密码错误。

appid没有过期什么的。

这怎么解决？

**Comment by lszh0147** [comment]
手机重新解绑退出，重新登陆，发现appid没变。再次执行action还是登录不了。

估计登录逻辑需要修改下：检测到登录失败--->先使用身份证后6位登录--->然后使用服务密码登录

**Comment by srcrs** [comment]
> 手机重新解绑退出，重新登陆，发现appid没变。再次执行action还是登录不了。
> 
> 估计登录逻辑需要修改下：检测到登录失败--->先使用身份证后6位登录--->然后使用服务密码登录

抱歉无法复现你所说的情景。

**Comment by lszh0147** [comment]
> 
> 
> > 手机重新解绑退出，重新登陆，发现appid没变。再次执行action还是登录不了。
> > 估计登录逻辑需要修改下：检测到登录失败--->先使用身份证后6位登录--->然后使用服务密码登录
> 
> 抱歉无法复现你所说的情景。

估计是我的账号触发了联通的安全机制吧。

我用手机营业厅登录，输入服务密码也是提示要用身份证后6位登录。

相信随着时间推移，我的情况不是个案。

**Comment by srcrs** [comment]
最近看看吧，最近看视频接口都已经更新了，很多任务都不好做了

**Comment by FuxkTME** [comment]
上周我也碰见过

**Comment by miracomangomanchuria** [comment]
改过密码吗？没改过的话，用初始密码就是这个样子的。

**Comment by lszh0147** [comment]
今天自己好了，估计联通抽风了。
