### ISSUE TITLE
任务全部完成，但邮件推送失败

### ISSUE THREAD

**Issue by ASFLY61** [srcrs/UnicomTask#39]
任务全部执行了，EMAIL_COVER值也设置看自己的邮箱，但推送失败
![屏幕截图 2021-02-24 195522](https://user-images.githubusercontent.com/31264679/108997355-76063b00-76da-11eb-8774-41e8a2182e0b.png)

**Comment by srcrs** [comment]
> 看自己的邮箱，但推送失败

是的，这个是由于发送邮箱API的问题。

**Comment by ASFLY61** [comment]
明白了
