### ISSUE TITLE
要使用短信验证码登录验证身份

### ISSUE THREAD

**Issue by 122507** [srcrs/UnicomTask#43]

**Comment by srcrs** [comment]
> 

appid没填写

**Comment by 122507** [comment]
重新填写了就可以了

**Comment by srcrs** [comment]
> 重新填写了就可以了

好的

**Comment by xiaogouxo** [comment]
有AppId也会出这个

**Comment by srcrs** [comment]
> 有AppId也会出这个,
> [2021-03-03 13:42:26,460]:INFO:{'reqtime': 1614750146460, 'simCount': '1', 'version': 'iphone_c@8.0004', 'mobile': b'****JgW1GgTu9fdLk=', 'netWay': 'wifi', 'isRemberPwd': 'false', 'appId': 'FF4C4CE2-****-****-****-B181C2961E1A', 'deviceId': 'b61f7efcba733583170df52d8f2f9f87521b3844d01ccbc774bbfa379eaeb3fa', 'pip': '192.168.1.4', 'password': 'b'****0=', 'deviceOS': '14.0.1', 'deviceBrand': 'iphone', 'deviceModel': 'iPad', 'remark4': '', 'keyVersion': '', 'deviceCode': 'B97CDE2A-D435-437D-9FEC-5D821A012972'}
> [2021-03-03 13:42:27,136]:INFO:【登录】: 尊敬的客户您好，请使用短信验证码登录进行身份验证!
> 不知道是不是因为这个请求被风控了，还是什么情况

你的appId填写的不对吧

**Comment by xiaogouxo** [comment]
是的，appId不对，
抓包联通APP
mobileService/activity/homepopUpActivity.htm?appId=xxxxxx，这个appId是不对的。
mobileService/customer/getclientconfig.htm?appId=xxxx，这个appId才是正确的appId，一大串字符串中介没有-分割
感谢指导，已经成功了
