### ISSUE TITLE
服务密码安全问题

### ISSUE THREAD

**Issue by QuincyC379** [srcrs/UnicomTask#44]
服务密码非常非常重要，现在使用的都是明码，能否添加下加解密程序。具体的可以参考：
`gpg --symmetric --cipher-algo AES256 my_secret.json`

[https://docs.github.com/en/actions/reference/encrypted-secrets](url)

**Comment by srcrs** [comment]
> 服务密码非常非常重要，现在使用的都是明码，能否添加下加解密程序。具体的可以参考：
> `gpg --symmetric --cipher-algo AES256 my_secret.json`
> 
> [https://docs.github.com/en/actions/reference/encrypted-secrets](url)

服务密码填写到secrets中，并没有明码。
