### ISSUE TITLE
大佬，请问支持多用户吗？

### ISSUE THREAD

**Issue by EdisonCC** [srcrs/UnicomTask#45]
大佬，请问支持多个用户一起跑吗？
需要怎么操作呀？谢谢！

**Comment by ssssssbn** [comment]
https://github.com/srcrs/UnicomTask/issues/1

**Comment by srcrs** [comment]
@EdisonCC 晚上更新云函数版本，以后将直接支持多用户。

**Comment by srcrs** [comment]
> 大佬，请问支持多个用户一起跑吗？
> 需要怎么操作呀？谢谢！

https://github.com/srcrs/UnicomTask/discussions/16
