### ISSUE TITLE
main问题？

### ISSUE THREAD

**Issue by xdcabc** [srcrs/UnicomTask#62]
Run echo "$USERS_COVER" > ./config.json
[2021-02-28 10:18:47,087]:ERROR:账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 341, in <module>
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 304, in readJson
    users = json.load(fp)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

    main("","")
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 313, in main
    for user in users:
TypeError: 'NoneType' object is not iterable
Error: Process completed with exit code 1.

**Comment by srcrs** [comment]
> Run echo "$USERS_COVER" > ./config.json
> [2021-02-28 10:18:47,087]:ERROR:账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)
> Traceback (most recent call last):
>   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 341, in <module>
> Traceback (most recent call last):
>   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 304, in readJson
>     users = json.load(fp)
>   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
> 
>     main("","")
>   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 313, in main
>     for user in users:
> TypeError: 'NoneType' object is not iterable
> Error: Process completed with exit code 1.

检查下你添加在Secrets的信息格式

**Comment by hezhizheng** [comment]
@srcrs 估计应该是没有向下兼容，同步上游代码才出现这个问题，暂时先代码回滚处理了......

**Comment by xdcabc** [comment]
> > 运行echo“ $ USERS_COVER”> ./config.json 
> > [ 2021-02-28 10：18：47,087]：ERROR：账号信息格式填充错误，原因为：期望值：第2行第1列（字符1）
> > Traceback（大多数最近一次调用）：
> > 在
> > Traceback中，文件“ /home/runner/work/UnicomTask/UnicomTask/main.py”，行341 （最近一次调用）：
> > 文件“ / home / runner / work / UnicomTask / UnicomTask / main”。 py”，第304行，在readJson
> > 用户中= json.load（fp）
> > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/ **init** .py”，第293行，在加载
> > 返回中负载（fp.read（），
> > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/ **init** .py”，行346），在负载中
> > 返回_default_decoder.decode
> > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py”，行337，解码
> > obj，结束= self.raw_decode（s，idx = _w（s，0 ）.end（））
> > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py”，行355，位于raw_decode中，
> > 引发JSONDecodeError（“ Expecting value”，s，err .value），从None 
> > json.decoder.JSONDecodeError：期望值：第2行第1列（字符1）
> > ```
> > main("","")
> > ```
> > 
> > 
> > 
> > 用户中的用户主文件“ /home/runner/work/UnicomTask/UnicomTask/main.py”，第313行：
> > TypeError：“ NoneType”对象不可迭代
> > 错误：进程已完成，退出代码为1。
> 
> 检查下你添加在Secrets的信息格式

啊  我找遍整个目录没找到Secrets文件

**Comment by srcrs** [comment]
> @srcrs 估计应该是没有向下兼容，同步上游代码才出现这个问题，暂时先代码回滚处理了......

是的，没有向下兼容，老代码和新代码添加和读取的方式不一样

**Comment by srcrs** [comment]
> > > 运行echo“ $ USERS_COVER”> ./config.json
> > > [ 2021-02-28 10：18：47,087]：ERROR：账号信息格式填充错误，原因为：期望值：第2行第1列（字符1）
> > > Traceback（大多数最近一次调用）：
> > > 在
> > > Traceback中，文件“ /home/runner/work/UnicomTask/UnicomTask/main.py”，行341 （最近一次调用）：
> > > 文件“ / home / runner / work / UnicomTask / UnicomTask / main”。 py”，第304行，在readJson
> > > 用户中= json.load（fp）
> > > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/ **init** .py”，第293行，在加载
> > > 返回中负载（fp.read（），
> > > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/ **init** .py”，行346），在负载中
> > > 返回_default_decoder.decode
> > > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py”，行337，解码
> > > obj，结束= self.raw_decode（s，idx = _w（s，0 ）.end（））
> > > 文件“ /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py”，行355，位于raw_decode中，
> > > 引发JSONDecodeError（“ Expecting value”，s，err .value），从None
> > > json.decoder.JSONDecodeError：期望值：第2行第1列（字符1）
> > > ```
> > > main("","")
> > > ```
> > > 
> > > 
> > > 用户中的用户主文件“ /home/runner/work/UnicomTask/UnicomTask/main.py”，第313行：
> > > TypeError：“ NoneType”对象不可迭代
> > > 错误：进程已完成，退出代码为1。
> > 
> > 
> > 检查下你添加在Secrets的信息格式
> 
> 啊 我找遍整个目录没找到Secrets文件

建议在读取一下github actions的部署教程。不要把信息填写到config.json里，注意一下个人信息安全，要复制config.json里面的内容，添加到Secrets中。

**Comment by xdcabc** [comment]
OMG是我大意了，好了，现在完成了
