### ISSUE TITLE
INFO:【登录】: 服务器链接超时，请稍后再试！

### ISSUE THREAD

**Issue by lqrqw** [srcrs/UnicomTask#64]
作者您好，第一次使用这个联通签到脚本。之前有使用过您的其它脚本，首先表示感谢。
运行这个脚本无论是本地nas或者action运行python main.py 都报错 [2021-03-01 00:50:50,085]:INFO:【登录】: 服务器链接超时，请稍后再试！
故意改成错的服务密码，会报密码错误，尝试验证码啥的。
nas上ping m.client.10010.com返回数据也正常。

**Comment by srcrs** [comment]
> 作者您好，第一次使用这个联通签到脚本。之前有使用过您的其它脚本，首先表示感谢。
> 运行这个脚本无论是本地nas或者action运行python main.py 都报错 [2021-03-01 00:50:50,085]:INFO:【登录】: 服务器链接超时，请稍后再试！
> 故意改成错的服务密码，会报密码错误，尝试验证码啥的。
> nas上ping m.client.10010.com返回数据也正常。

有可能是你们当地联通服务器在维护的，早上八点过后再试一下。

**Comment by lqrqw** [comment]
OK了，可能是月初联通服务器问题，谢谢回复
