### ISSUE TITLE
云函数+多账户+钉钉机器人推送存在乱码

### ISSUE THREAD

**Issue by Truelovefortony** [srcrs/UnicomTask#65]
作者您好，在云函数+多账户+钉钉机器人推送的环境下，钉钉机器人消息前面会多很多乱码，谢谢~

![avatar](https://raw.githubusercontent.com/Truelovefortony/UnicomTask/main/11.jpg)

**Comment by Truelovefortony** [comment]
补充：电脑版钉钉显示正常，手机版前面就会乱码

**Comment by srcrs** [comment]
> 补充：电脑版钉钉显示正常，手机版前面就会乱码

好的，我查看一下。

**Comment by srcrs** [comment]
> 补充：电脑版钉钉显示正常，手机版前面就会乱码

更新代码，看一下是否解决了。

**Comment by srcrs** [comment]
@Truelovefortony 你使用云函数，报找不到rsa==4.7这个错误了吗？

**Comment by Truelovefortony** [comment]
是的，云函数日志找不到rsa
日志:

START RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0

ERROR RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/main.py\", line 6, in \u003cmodule\u003e\n    import requests,json,time,re,login,logging,traceback,os,random,notify\n  File \"/var/user/login.py\", line 6, in \u003cmodule\u003e\n    import base64,rsa,time,requests,logging,traceback,os\nModuleNotFoundError: No module named 'rsa'","statusCode":443}

END RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0

Report RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by srcrs** [comment]
> 是的，云函数日志找不到rsa
> 日志:
> 
> START RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0
> 
> ERROR RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/main.py\", line 6, in \u003cmodule\u003e\n    import requests,json,time,re,login,logging,traceback,os,random,notify\n  File \"/var/user/login.py\", line 6, in \u003cmodule\u003e\n    import base64,rsa,time,requests,logging,traceback,os\nModuleNotFoundError: No module named 'rsa'","statusCode":443}
> 
> END RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0
> 
> Report RequestId:b4f408a9-b151-461d-990b-3c93fe49acd0 Duration:0ms Memory:128MB MemUsage:0.000000MB

奇了怪了，我这边是正常的，你把rsa版本换到4.7.1试一下，或者4.5

**Comment by Truelovefortony** [comment]
Hello~RSA改成4.5正常了，钉钉消息也正常了~

**Comment by Truelovefortony** [comment]
Hello~云函数RSA改成4.5正常了，钉钉消息正常了
