### ISSUE TITLE
冬奥积分领取失败

### ISSUE THREAD

**Issue by czlycpf02** [srcrs/UnicomTask#68]
大佬您好，请问冬奥积分显示“领取失败，成功”，实际上并未领取是怎么回事？

**Comment by srcrs** [comment]
> 大佬您好，请问冬奥积分显示“领取失败，成功”，实际上并未领取是怎么回事？

尝试再次运行试试

**Comment by LuzMasonj** [comment]
这个冬奥积分似乎没有什么用啊
