### ISSUE TITLE
请教怎么设置邮件接收的间隔时间呀，虽然是UnicomTask每日报表，但是十几分钟收到一封邮件有点太频繁了

### ISSUE THREAD

**Issue by back11** [srcrs/UnicomTask#69]
![image.png](https://pic.iask.cn/fimg/613111345446.jpg)
![image.png](https://pic.iask.cn/fimg/244001345492.jpg)
就是每日提醒一次就行，求助各位大佬！

**Comment by srcrs** [comment]
> ![image.png](https://camo.githubusercontent.com/a41d5a17766e9a24b0ef2002c259cc04e6f2b5fb9292e66a6df280e088097157/68747470733a2f2f7069632e6961736b2e636e2f66696d672f3631333131313334353434362e6a7067)
> ![image.png](https://camo.githubusercontent.com/da417b7eca9895ac552dc213283a8ccb0c5856f7115d91b39bf67798032cc5f1/68747470733a2f2f7069632e6961736b2e636e2f66696d672f3234343030313334353439322e6a7067)
> 就是每日提醒一次就行，求助各位大佬！

不会啊，程序运行几次就会发几次邮件

**Comment by davidelectricfree** [comment]
你自己更新代码了吧，这个项目的主程序的action的触发只要你一push就触发了，不想触发那么频繁把push删掉，或者在本地改好了代码再push。

**Comment by back11** [comment]
好的，感谢，终于理解了
