### ISSUE TITLE
requirement文件 rsa版本腾讯云函数更新有问题

### ISSUE THREAD

**Issue by vonxing** [srcrs/UnicomTask#70]
执行这个的时候action提示如下
  Could not find a version that satisfies the requirement rsa==4.7 (from -r ./requirements.txt (line 3)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)

**Comment by srcrs** [comment]
> 执行这个的时候action提示如下
> Could not find a version that satisfies the requirement rsa==4.7 (from -r ./requirements.txt (line 3)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)

那你换到4.5试一下吧，可以的话，一会都改成4.5的

**Comment by srcrs** [comment]
> > 执行这个的时候action提示如下
> > Could not find a version that satisfies the requirement rsa==4.7 (from -r ./requirements.txt (line 3)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
> 
> 那你换到4.5试一下吧，可以的话，一会都改成4.5的

rsa4.7版本找不到，实际上在云函数中是否有rsa模块？

**Comment by vonxing** [comment]
> > > 执行这个的时候action提示如下
> > > Could not find a version that satisfies the requirement rsa==4.7 (from -r ./requirements.txt (line 3)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
> > 
> > 
> > 那你换到4.5试一下吧，可以的话，一会都改成4.5的
> 
> rsa4.7版本找不到，实际上在云函数中是否有rsa模块？

云函数上也提示找不到rsa模块,我这边github actios卡住了  后面就没测试了

**Comment by vonxing** [comment]
> > > > 执行这个的时候action提示如下
> > > > Could not find a version that satisfies the requirement rsa==4.7 (from -r ./requirements.txt (line 3)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
> > > 
> > > 
> > > 那你换到4.5试一下吧，可以的话，一会都改成4.5的
> > 
> > 
> > rsa4.7版本找不到，实际上在云函数中是否有rsa模块？
> 
> 云函数上也提示找不到rsa模块,我这边github actios卡住了 后面就没测试了

刚才实测现在跑云函数是可以正常运行的
