### ISSUE TITLE
deploy时报错

### ISSUE THREAD

**Issue by borpubi** [srcrs/UnicomTask#78]
表现：deploy时报 ：ERROR:账号信息格式填写错误，原因为: Expecting value: line 2 column 1 (char 1)
secret内容如下：
`[
    {
        "username": "1853823xxxx",
        "password": "12345678",
        "appId": "64cdd06dbf1ba0c9db682c64ebcf3ec76c888b9693767b2811e317371d95064c2c7ede00d22df3f31f85734dba9bbc64390a25013541eef67a44172567d226xxxxxxxxxxxxxxxxxxxxxx"
    }
]`

多次核对ReadMe,感觉自己应该填写正确了，麻烦大佬帮忙看一下是哪一步有问题，谢谢。
报错截图如下：
![image](https://user-images.githubusercontent.com/28093885/109618165-31631f80-7b72-11eb-83ec-c37c70f2055b.png)

**Comment by borpubi** [comment]
看报错提示应该是账号密码的格式不正确，但核对ReadMe.MD 感觉应该填写是正确的啊。

**Comment by borpubi** [comment]
反复重新修改secret后push，终于成功b ，问题是：还是不知道是哪一步做错了……

**Comment by srcrs** [comment]
> 看报错提示应该是账号密码的格式不正确，但核对ReadMe.MD 感觉应该填写是正确的啊。

有可能是你重复运行旧的工作流，环境变量还是以前的。
