### ISSUE TITLE
云函数telegram通知问题

### ISSUE THREAD

**Issue by JohnED512** [srcrs/UnicomTask#81]
部署默认的云函数地区是广州，但因为墙的原因telegram通知失败，希望把部署地区改为香港或其他地区

**Comment by srcrs** [comment]
> 部署默认的云函数地区是广州，但因为墙的原因telegram通知失败，希望把部署地区改为香港或其他地区

这个确实没考虑到，建议使用了tg推送的话，自己手动改一下吧，不过大陆以外地址，可能会造成一些未知问题。

**Comment by mmkakac** [comment]
大佬，我部署完之后 也没有红叉，腾讯云函数里面也没看到，咋整？

**Comment by srcrs** [comment]
> 大佬，我部署完之后 也没有红叉，腾讯云函数里面也没看到，咋整？

一会我看看你的日志。

**Comment by mmkakac** [comment]
> > 大佬，我部署完之后也没有红叉，腾讯云函数里面也没看到，咋整？
> 
> 一会我看看你的日志。

看起来没啥问题啊

**Comment by srcrs** [comment]
> > > 大佬，我部署完之后也没有红叉，腾讯云函数里面也没看到，咋整？
> > 
> > 
> > 一会我看看你的日志。
> 
> 看起来没啥问题啊

部署至腾讯云需要填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY两个secrets，跳过部署

**Comment by srcrs** [comment]
@mmkakac 你没填写这两个值啊

**Comment by mmkakac** [comment]
![image](https://user-images.githubusercontent.com/78542776/109766478-2fac6100-7c31-11eb-9313-703159176013.png)
不是这个吗？

**Comment by mmkakac** [comment]
> @mmkakac 你没填写这两个值啊

大佬，这里我填了几次了

**Comment by srcrs** [comment]
> > @mmkakac 你没填写这两个值啊
> 
> 大佬，这里我填了几次了

添加的地方错了，应该是这里
![5953cc018d5b98071b7a61ebc2e0d1f](https://user-images.githubusercontent.com/49332985/109767329-58812600-7c32-11eb-826c-552dd26cc104.png)

**Comment by mmkakac** [comment]
> > > @mmkakac 你没填写这两个值啊
> > 
> > 
> > 大佬，这里我填了几次了
> 
> 添加的地方错了，应该是这里
> ![5953cc018d5b98071b7a61ebc2e0d1f](https://user-images.githubusercontent.com/49332985/109767329-58812600-7c32-11eb-826c-552dd26cc104.png)

应该可以了，非常感谢，辛苦大佬了

**Comment by if1y** [comment]
强烈建议刚才默认香港。
Github Actions 的容器地点在美国，如果腾讯云函数香港会出问题，那么 Actions 只会问题更大。

**Comment by JohnED512** [comment]
> 强烈建议改成默认香港。
> Github Actions 的容器地点在美国，如果腾讯云函数香港会出问题，那么 Actions 只会问题更大。

我发了个PR，等大佬回复吧

**Comment by srcrs** [comment]
> 强烈建议改成默认香港。
> Github Actions 的容器地点在美国，如果腾讯云函数香港会出问题，那么 Actions 只会问题更大。

是这样的，在Actions运行，有时候会莫名出现"接口放刷策略"的问题，但是在本地网络，却很少会出现，所以有了云函数版。通知只是个辅助作用，目的还是任务的稳定执行。
如果确实需要设置香港地区，我可以把部署云函数Actions改为可以填写地区的形式，但默认地区仍是国内。

**Comment by if1y** [comment]
那好吧，我目前使用了几个同类脚本，Actions 环境，倒是没发现什么问题。
不过容器地点变成 secrets 就不必了，这个自己改改就好，不难。  @srcrs 

除了改容器位置，也可以考虑改 tg api，反代一下就行了，国内访问没什么问题 @JohnED512

**Comment by mmkakac** [comment]
大佬，咋没有每天小游戏领3g呀

**Comment by srcrs** [comment]
> 那好吧，我目前使用了几个同类脚本，Actions 环境，倒是没发现什么问题。
> 不过容器地点变成 secrets 就不必了，这个自己改改就好，不难。  @srcrs 
> 
> 除了改容器位置，也可以考虑改 tg api，反代一下就行了，国内访问没什么问题 @JohnED512 

有更好的解决方案欢迎提pr哦，tg我平常用的不多，不太了解。目前发现了企业微信应用通知，无需借助第三方，就可以推送到普通微信，近期可能会到添加到该项目。

**Comment by srcrs** [comment]
> 大佬，咋没有每天小游戏领3g呀

能力不够😂

**Comment by if1y** [comment]
Telegram 通知日志排版怎么这么多空行，是因为云函数执行的 BUG 吗
![image](https://user-images.githubusercontent.com/32222791/109907728-dd754980-7cdd-11eb-955a-ad06ed80d6ab.png)
@srcrs

**Comment by srcrs** [comment]
> Telegram 通知日志排版怎么这么多空行，是因为云函数执行的 BUG 吗
> ![image](https://user-images.githubusercontent.com/32222791/109907728-dd754980-7cdd-11eb-955a-ad06ed80d6ab.png)
> @srcrs

这是多了两行吗？

**Comment by if1y** [comment]
> 这是多了两行吗？

对，每行内容之间有2行空白
