### ISSUE TITLE
签到-免费领-免费领流量，1G日包目前3月1日可领，3月3日可领

### ISSUE THREAD

**Issue by meilfy** [srcrs/UnicomTask#84]
签到-免费领-免费领流量，1G日包目前3月1日可领，3月3日可领

**Comment by srcrs** [comment]
> 签到-免费领-免费领流量，1G日包目前3月1日可领，3月3日可领

好的，谢谢提供活动来源，已经添加上了。

**Comment by SymonChu** [comment]
1G日包能自动激活吗？

**Comment by bearcony** [comment]
又不是所有的人，都需要马上激活。连点开激活都懒啊😯

**Comment by srcrs** [comment]
> 1G日包能增加自动激活吗？

我还没想好，如何智能、人性化的去自动激活，绝不能简简单单的去自动激活，正如楼下所说，并不是所有的人都需要马上激活，这个领取的流量，更多的是做一个备份、急用。
不同的流量包到期时间都有所不同，有的一年、一个月、几天的有效期。在"我的流量"栏中，还分为日流量、多日流量、月流量，日流量每天又能兑换多种额度，情况有些复杂。
最近也比较忙，等空闲下来会考虑这一功能，并将其实现。
最后感谢你的支持。
