### ISSUE TITLE
云函数执行失败

### ISSUE THREAD

**Issue by EdisonCC** [srcrs/UnicomTask#89]
部署完成之后，点击测试，执行摘要 反馈 测试失败

`执行日志
START RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83

ERROR RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/main.py\", line 6, in \u003cmodule\u003e\n    import requests,json,time,re,login,logging,traceback,os,random,notify\n  File \"/var/user/login.py\", line 6, in \u003cmodule\u003e\n    import base64,rsa,time,requests,logging,traceback,os\nModuleNotFoundError: No module named 'rsa'","statusCode":443}

END RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83

Report RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83 Duration:0ms Memory:128MB MemUsage:0.000000MB`

**Comment by srcrs** [comment]
> 部署完成之后，点击测试，执行摘要 反馈 测试失败
> 
> `执行日志
> START RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83
> 
> ERROR RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/main.py\", line 6, in \u003cmodule\u003e\n    import requests,json,time,re,login,logging,traceback,os,random,notify\n  File \"/var/user/login.py\", line 6, in \u003cmodule\u003e\n    import base64,rsa,time,requests,logging,traceback,os\nModuleNotFoundError: No module named 'rsa'","statusCode":443}
> 
> END RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83
> 
> Report RequestId:fd32a2c9-89d1-4959-b6ba-229fa51b5b83 Duration:0ms Memory:128MB MemUsage:0.000000MB`

这个问题很奇怪，缺少rsa模块，重新部署下看看。

**Comment by EdisonCC** [comment]
删除之后，重新fork再次部署就可以了，谢谢！

**Comment by srcrs** [comment]
> 删除之后，重新fork再次部署就可以了，谢谢！

好的
