### ISSUE TITLE
关于每日任务中游戏积分

### ISSUE THREAD

**Issue by hj207255** [srcrs/UnicomTask#95]
你好，请问可以添加每日任务中的游戏积分吗？

**Comment by srcrs** [comment]
> 你好，请问可以添加每日任务中的游戏积分吗？

本来就有的啊

**Comment by hj207255** [comment]
> > 你好，请问可以添加每日任务中的游戏积分吗？
> 
> 本来就有的啊

就是玩5分钟网页游戏那个

**Comment by hj207255** [comment]
> > 你好，请问可以添加每日任务中的游戏积分吗？
> 
> 本来就有的啊

![image](https://user-images.githubusercontent.com/40658577/109914502-1831ae80-7ceb-11eb-852b-a96a705b8b0e.png)
